---
title: "Initial Analysisv1"
author: "Teena Thomas"
date: "2024-02-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading necessary library

```{r}
library(haven)
library (survey)
library(sf)
library(tmap)
library(ggplot2)
library(dplyr)
library(survey)
library(rnaturalearth)
library(rnaturalearthdata)
library(tidyverse)


```

## Reading data

```{r}
data <- read_dta("IAKR7EFL.DTA")
head (data)

```

```{r}

unique(data$v445) # na is not applicable but what to do with flagged cases?

unique(data$v155) # no missing or na values

unique(data$v438)

```


## Reading and handling birth weight data

```{r}
head (data$m19)

```


```{r}
m19_counts <- data %>%
  summarise(
    count_9996 = sum(m19 == 9996, na.rm = TRUE),
    count_9998 = sum(m19 == 9998, na.rm = TRUE),
    count_NA = sum(is.na(m19))
  )

print(m19_counts)
```


```{r}
unique(data$b0)
```



```{r}
# Filtered the 9996 and 9998 from m19 values and included only single births and filtered out twins or multiple births
data_filtered <- data %>%
  filter(b0 == 0) %>%
  filter(!(m19 %in% c(9996, 9998)))
summary(data_filtered$m19)
```




## Creating the data subset with relevant variables


```{r}
# All the relevant variables for the analysis has been included in the data subset
relevant_vars <- c("v005", "v021", "v022", "v023", "v024", "v012", "v106", "v130", "v131","sdist", 
                   "v190", "v437", "v438", "v445", "v155", "v501", "v228", "v463z", "v716", 
                   "v025", "v101", "v113", "v116", "v127", "v161", "m1", "m14", "m42a", "m42c", "m42d", "m42e", "m2a", "m2b",
                   "m2g", "m2h", "m2i", "m2j", "m2k", "m2n", "m3a", "m3b", "m3c", "m3h",  "m3k",
                   "m3n", "m43", "m44", "m45", "m46", "m15", "m17", "m18","m19", "b4", "s220a", "v201", "b11", "b0", "b2")

data_subset <- data_filtered %>%
  select(all_of(relevant_vars))

# Then I created a survey design object
survey_design <- svydesign(id = ~v021, strata = ~v022, weights = ~v005, data = data_subset, nest = TRUE)

options(survey.lonely.psu = "adjust")

# To calculate the prevalence of low birth weight (less than 2500 grams)
low_birth_weight <- svymean(~I(m19 < 2500), design = survey_design, na.rm = TRUE)
```



```{r}
# Extracted only the values of prevalence and their standard errors of low birth weight
low_birth_weight_true <- coef(low_birth_weight)["I(m19 < 2500)TRUE"] * 100
low_birth_weight_se <- SE(low_birth_weight)["I(m19 < 2500)TRUE"] * 100

state_prevalence_true <- prevalence_by_state %>%
  select(v024, `I(m19 < 2500)TRUE`, `se.I(m19 < 2500)TRUE`) %>%
  mutate(`I(m19 < 2500)TRUE` = `I(m19 < 2500)TRUE` * 100,
         `se.I(m19 < 2500)TRUE` = `se.I(m19 < 2500)TRUE` * 100)

district_prevalence_true <- prevalence_by_district %>%
  select(sdist, `I(m19 < 2500)TRUE`, `se.I(m19 < 2500)TRUE`) %>%
  mutate(`I(m19 < 2500)TRUE` = `I(m19 < 2500)TRUE` * 100,
         `se.I(m19 < 2500)TRUE` = `se.I(m19 < 2500)TRUE` * 100)

# Print results
cat("Overall Prevalence of Low Birth Weight (LBW):", round(low_birth_weight_true, 2), "%\n")
cat("Standard Error:", round(low_birth_weight_se, 2), "%\n\n")

cat("Prevalence by State:\n")
print(state_prevalence_true)

cat("\nPrevalence by District:\n")
print(district_prevalence_true)

```

### Creating Maps for low birth weight prevelance at the state level

```{r}
# Loaded state-level shapefile from GADM
india_states <- st_read("gadm41_IND_1.json")
```


```{r}
india_districts <- st_read("gadm41_IND_2.json")
head(india_districts)
```


```{r}
unique(india_districts$NAME_2)
```


```{r}
# Create a vector with all the district names
nfhs_district_names <- c(
  "Kupwara", "Badgam", "Leh(Ladakh)", "Kargil", "Punch", "Rajouri", "Kathua", "Baramula", "Bandipore", "Srinagar", 
  "Ganderbal", "Pulwama", "Shupiyan", "Anantnag", "Kulgam", "Doda", "Ramban", "Kishtwar", "Udhampur", "Reasi", 
  "Jammu", "Samba", "Chamba", "Kangra", "Lahul & Spiti", "Kullu", "Mandi", "Hamirpur", "Una", "Bilaspur", 
  "Solan", "Sirmaur", "Shimla", "Kinnaur", "Kapurthala", "Jalandhar", "Hoshiarpur", "Shahid Bhagat Singh Nagar", 
  "Fatehgarh Sahib", "Ludhiana", "Moga", "Muktsar", "Faridkot", "Bathinda", "Mansa", "Patiala", "Amritsar", 
  "Tarn Taran", "Rupnagar", "Sahibzada Ajit Singh Nagar", "Sangrur", "Barnala", "Chandigarh", "Uttarkashi", 
  "Chamoli", "Rudraprayag", "Tehri Garhwal", "Dehradun", "Garhwal", "Pithoragarh", "Bageshwar", "Almora", 
  "Champawat", "Nainital", "Udham Singh Nagar", "Hardwar", "Panchkula", "Ambala", "Yamunanagar", "Kurukshetra", 
  "Kaithal", "Karnal", "Panipat", "Sonipat", "Jind", "Fatehabad", "Sirsa", "Hisar", "Rohtak", "Jhajjar", 
  "Mahendragarh", "Rewari", "Gurgaon", "Mewat", "Faridabad", "Palwal", "Ganganagar", "Hanumangarh", "Bikaner", 
  "Churu", "Jhunjhunun", "Alwar", "Bharatpur", "Dhaulpur", "Karauli", "Sawai Madhopur", "Dausa", "Jaipur", 
  "Sikar", "Nagaur", "Jodhpur", "Jaisalmer", "Barmer", "Jalor", "Sirohi", "Pali", "Ajmer", "Tonk", "Bundi", 
  "Bhilwara", "Rajsamand", "Dungarpur", "Banswara", "Chittaurgarh", "Kota", "Baran", "Jhalawar", "Udaipur", 
  "Pratapgarh", "Saharanpur", "Bijnor", "Rampur", "Jyotiba Phule Nagar", "Meerut", "Baghpat", "Gautam Buddha Nagar", 
  "Bulandshahr", "Aligarh", "Mahamaya Nagar", "Mathura", "Agra", "Firozabad", "Mainpuri", "Bareilly", "Pilibhit", 
  "Shahjahanpur", "Kheri", "Sitapur", "Hardoi", "Unnao", "Lucknow", "Farrukhabad", "Kannauj", "Etawah", "Auraiya", 
  "Kanpur Dehat", "Kanpur Nagar", "Jalaun", "Jhansi", "Lalitpur", "Hamirpur", "Mahoba", "Banda", "Chitrakoot", 
  "Fatehpur", "Pratapgarh", "Kaushambi", "Allahabad", "Bara Banki", "Faizabad", "Ambedkar Nagar", "Bahraich", 
  "Shrawasti", "Balrampur", "Gonda", "Siddharthnagar", "Basti", "Sant Kabir Nagar", "Mahrajganj", "Gorakhpur", 
  "Kushinagar", "Deoria", "Azamgarh", "Mau", "Ballia", "Jaunpur", "Ghazipur", "Chandauli", "Varanasi", 
  "Sant Ravidas Nagar (Bhadohi)", "Mirzapur", "Sonbhadra", "Etah", "Kanshiram Nagar", "Pashchim Champaran", 
  "Purba Champaran", "Sheohar", "Sitamarhi", "Madhubani", "Supaul", "Araria", "Kishanganj", "Purnia", 
  "Katihar", "Madhepura", "Saharsa", "Darbhanga", "Muzaffarpur", "Gopalganj", "Siwan", "Saran", "Vaishali", 
  "Samastipur", "Begusarai", "Khagaria", "Bhagalpur", "Banka", "Munger", "Lakhisarai", "Sheikhpura", "Nalanda", 
  "Patna", "Bhojpur", "Buxar", "Kaimur (Bhabua)", "Rohtas", "Aurangabad", "Gaya", "Nawada", "Jamui", "Jehanabad", 
  "Arwal", "North District", "West District", "South District", "East District", "Tawang", "West Kameng", 
  "East Kameng", "Papum Pare", "Upper Subansiri", "Upper Siang", "Changlang", "Lower Subansiri", "Dibang Valley", 
  "Lower Dibang Valley", "Anjaw", "Mon", "Mokokchung", "Zunheboto", "Wokha", "Dimapur", "Phek", "Tuensang", 
  "Longleng", "Kiphire", "Kohima", "Peren", "Senapati", "Tamenglong", "Churachandpur", "Bishnupur", "Thoubal", 
  "Imphal West", "Imphal East", "Ukhrul", "Chandel", "Mamit", "Kolasib", "Aizawl", "Champhai", "Serchhip", 
  "Lunglei", "Lawngtlai", "Saiha", "Dhalai", "South Garo Hills", "Ribhoi", "East Khasi Hills", "Kokrajhar", 
  "Goalpara", "Barpeta", "Morigaon", "Lakhimpur", "Dhemaji", "Tinsukia", "Dibrugarh", "Golaghat", "Dima Hasao", 
  "Cachar", "Karimganj", "Hailakandi", "Bongaigaon", "Chirang", "Kamrup", "Kamrup Metropolitan", "Nalbari", 
  "Baksa", "Darrang", "Udalguri", "Darjiling", "Jalpaiguri", "Koch Bihar", "Uttar Dinajpur", "Dakshin Dinajpur", 
  "Maldah", "Murshidabad", "Birbhum", "Nadia", "North Twenty Four Parganas", "Hugli", "Bankura", "Puruliya", 
  "Haora", "Kolkata", "South Twenty Four Parganas", "Paschim Medinipur", "Purba Medinipur", "Garhwa", "Chatra", 
  "Kodarma", "Giridih", "Deoghar", "Godda", "Sahibganj", "Pakur", "Dhanbad", "Bokaro", "Lohardaga", 
  "Purbi Singhbhum", "Palamu", "Latehar", "Hazaribagh", "Ramgarh", "Dumka", "Jamtara", "Ranchi", "Khunti", 
  "Gumla", "Simdega", "Pashchimi Singhbhum", "Saraikela-Kharsawan", "Bargarh", "Jharsuguda", "Sambalpur", 
  "Debagarh", "Sundargarh", "Kendujhar", "Mayurbhanj", "Baleshwar", "Bhadrak", "Kendrapara", "Jagatsinghapur", 
  "Cuttack", "Jajapur", "Dhenkanal", "Anugul", "Nayagarh", "Khordha", "Puri", "Ganjam", "Gajapati", 
  "Kandhamal", "Baudh", "Subarnapur", "Balangir", "Nuapada", "Kalahandi", "Rayagada", "Nabarangapur", 
  "Koraput", "Malkangiri", "Koriya", "Jashpur", "Raigarh", "Korba", "Janjgir - Champa", "Kabeerdham", 
  "Rajnandgaon", "Mahasamund", "Dhamtari", "Uttar Bastar Kanker", "Narayanpur", "Bijapur", "Sheopur", 
  "Morena", "Bhind", "Gwalior", "Datia", "Shivpuri", "Tikamgarh", "Chhatarpur", "Panna", "Sagar", "Damoh", 
  "Satna", "Rewa", "Umaria", "Neemuch", "Mandsaur", "Ratlam", "Ujjain", "Dewas", "Dhar", "Indore", 
  "Khargone (West Nimar)", "Barwani", "Rajgarh", "Vidisha", "Bhopal", "Sehore", "Raisen", "Betul", 
  "Harda", "Hoshangabad", "Katni", "Jabalpur", "Narsimhapur", "Dindori", "Mandla", "Chhindwara", "Seoni", 
  "Balaghat", "Guna", "Ashoknagar", "Shahdol", "Anuppur", "Sidhi", "Singrauli", "Jhabua", "Alirajpur", 
  "Khandwa (East Nimar)", "Burhanpur", "Kachchh", "Banas Kantha", "Patan", "Mahesana", "Gandhinagar", 
  "Porbandar", "Amreli", "Anand", "Dohad", "Narmada", "Bharuch", "The Dangs", "Navsari", "Valsad", "Surat", 
  "Tapi", "Diu", "Daman", "Dadra & Nagar Haveli", "Nandurbar", "Dhule", "Jalgaon", "Buldana", "Akola", 
  "Washim", "Amravati", "Wardha", "Nagpur", "Bhandara", "Gondiya", "Gadchiroli", "Chandrapur", "Yavatmal", 
  "Nanded", "Hingoli", "Parbhani", "Jalna", "Aurangabad", "Nashik", "Mumbai Suburban", "Mumbai", 
  "Raigarh", "Pune", "Ahmadnagar", "Bid", "Latur", "Osmanabad", "Solapur", "Satara", "Ratnagiri", 
  "Sindhudurg", "Kolhapur", "Sangli", "Srikakulam", "Vizianagaram", "Visakhapatnam", "East Godavari", 
  "West Godavari", "Krishna", "Guntur", "Prakasam", "Sri Potti Sriramulu Nellore", "Y.S.R.", "Kurnool", 
  "Anantapur", "Chittoor", "Belgaum", "Bagalkot", "Bijapur", "Bidar", "Raichur", "Koppal", "Gadag", 
  "Dharwad", "Uttara Kannada", "Haveri", "Bellary", "Chitradurga", "Davanagere", "Shimoga", "Udupi", 
  "Chikmagalur", "Tumkur", "Bangalore", "Mandya", "Hassan", "Dakshina Kannada", "Kodagu", "Mysore", 
  "Chamarajanagar", "Gulbarga", "Yadgir", "Kolar", "Chikkaballapura", "Bangalore Rural", "Ramanagara", 
  "North Goa", "South Goa", "Lakshadweep", "Kasaragod", "Kannur", "Wayanad", "Kozhikode", "Malappuram", 
  "Palakkad", "Thrissur", "Ernakulam", "Idukki", "Kottayam", "Alappuzha", "Pathanamthitta", "Kollam", 
  "Thiruvananthapuram", "Thiruvallur", "Chennai", "Kancheepuram", "Vellore", "Tiruvannamalai", "Viluppuram", 
  "Salem", "Namakkal", "Erode", "The Nilgiris", "Dindigul", "Karur", "Tiruchirappalli", "Perambalur", 
  "Ariyalur", "Cuddalore", "Nagapattinam", "Thiruvarur", "Thanjavur", "Pudukkottai", "Sivaganga", 
  "Madurai", "Theni", "Virudhunagar", "Ramanathapuram", "Thoothukkudi", "Tirunelveli", "Kanniyakumari", 
  "Dharmapuri", "Krishnagiri", "Coimbatore", "Tiruppur", "Yanam", "Puducherry", "Mahe", "Karaikal", 
  "Nicobars", "North & Middle Andaman", "South Andaman", "East Siang", "Kra Daadi", "Kurung Kumey", 
  "Lohit", "Longding", "Namsai", "Siang", "Tirap", "West Siang", "Biswanath", "Charaideo", "Dhubri", 
  "Hojai", "Jorhat", "Karbi Anglong", "Majuli", "Nagaon", "Sivasagar", "Sonitpur", "South Salmara Mancachar", 
  "West Karbi Anglong", "Balod", "Baloda Bazar", "Balrampur", "Bastar", "Bemetara", "Bilaspur", 
  "Dantewada", "Durg", "Gariyaband", "Kodagaon", "Mungeli", "Raipur", "Sukma", "Surajpur", "Surguja", 
  "Central", "East", "New Delhi", "North", "North East", "North West", "Shahdara", "South", "South East", 
  "South West", "West", "Ahmadabad", "Aravali", "Bhavnagar", "Botad", "Chhota Udaipur", "Devbhumi Dwarka", 
  "Gir Somnath", "Jamnagar", "Junagadh", "Kheda", "Mahisagar", "Morbi", "Panch Mahals", "Rajkot", 
  "Sabar Kantha", "Surendranagar", "Vadodara", "Bhiwani", "Charkhi Dadri", "Agar Malwa", "Shajapur", 
  "Palghar", "Thane", "East Garo Hills", "East Jantia Hills", "North Garo Hills", "South West Garo Hills", 
  "South West Khasi Hills", "West Garo Hills", "West Jaintia Hills", "West Khasi Hills", "Fazilka", 
  "Firozpur", "Gurdaspur", "Pathankot", "Adilabad", "Bhadradri Kothagudem", "Hyderabad", "Jagitial", 
  "Jangoan", "Jayashankar Bhupalapally", "Jogulamba Gadwal", "Kamareddy", "Karimnagar", "Khammam", 
  "Komaram Bheem Asifabad", "Mahabubabad", "Mahabubnagar", "Mancherial", "Medak", "Medchal-Malkajgiri", 
  "Nagarkurnool", "Nalgonda", "Nirmal", "Nizamabad", "Peddapalli", "Rajanna Sircilla", "Ranga Reddy", 
  "Sangareddy", "Siddipet", "Suryapet", "Vikarabad", "Wanaparthy", "Warangal Rural", "Warangal Urban", 
  "Yadadri Bhuvanagiri", "Gomati", "Khowai", "North Tripura", "Sepahijala", "South Tripura", "Unakoti", 
  "West Tripura", "Amethi", "Budaun", "Ghaziabad", "Hapur", "Moradabad", "Muzaffarnagar", "Rae Bareli", 
  "Sambhal", "Shamli", "Sultanpur", "Paschim Barddhaman", "Purba Barddhaman"
)

# Create a vector with all the district names
gadm_district_names <- c(
  "NicobarIslands", "NorthandMiddleAndaman", "SouthAndaman", "Anantapur", "Chittoor",
  "EastGodavari", "Guntur", "Krishna", "Kurnool", "Nellore",
  "Prakasam", "Srikakulam", "Visakhapatnam", "Vizianagaram", "WestGodavari",
  "Y.S.R.", "Anjaw", "Changlang", "DibangValley", "EastKameng",
  "EastSiang", "KurungKumey", "Lohit", "Longding", "LowerDibangValley",
  "LowerSubansiri", "Namsai", "PapumPare", "Tawang", "Tirap",
  "UpperSiang", "UpperSubansiri", "WestKameng", "WestSiang", "Baksa",
  "Barpeta", "Bongaigaon", "Cachar", "Chirang", "Darrang",
  "Dhemaji", "Dhubri", "Dibrugarh", "DimaHasao", "Goalpara",
  "Golaghat", "Hailakandi", "Jorhat", "Kamrup", "KamrupMetropolitan",
  "KarbiAnglong", "Karimganj", "Kokrajhar", "Lakhimpur", "Morigaon",
  "Nagaon", "Nalbari", "Sivasagar", "Sonitpur", "Tinsukia",
  "Udalguri", "Araria", "Arwal", "Aurangabad", "Banka",
  "Begusarai", "Bhagalpur", "Bhojpur", "Buxar", "Darbhanga",
  "Gaya", "Gopalganj", "Jamui", "Jehanabad", "Kaimur",
  "Katihar", "Khagaria", "Kishanganj", "Lakhisarai", "Madhepura",
  "Madhubani", "Munger", "Muzaffarpur", "Nalanda", "Nawada",
  "PashchimChamparan", "Patna", "PurbaChamparan", "Purnia", "Rohtas",
  "Saharsa", "Samastipur", "Saran", "Sheikhpura", "Sheohar",
  "Sitamarhi", "Siwan", "Supaul", "Vaishali", "Chandigarh",
  "Balod", "BalodaBazar", "Balrampur", "Bastar", "Bemetara",
  "Bijapur", "Bilaspur", "Dantewada", "Dhamtari", "Durg",
  "Gariaband", "Janjgir-Champa", "Jashpur", "Kabeerdham", "Kondagaon",
  "Korba", "Koriya", "Mahasamund", "Mungeli", "Narayanpur",
  "Raigarh", "Raipur", "Rajnandgaon", "Sukma", "Surajpur",
  "Surguja", "UttarBastarKanker", "DadraandNagarHaveli", "Daman", "Diu",
  "NorthGoa", "SouthGoa", "Ahmadabad", "Amreli", "Anand",
  "Aravalli", "BanasKantha", "Bharuch", "Bhavnagar", "Botad",
  "ChhotaUdaipur", "Dahod", "DevbhumiDwarka", "Gandhinagar", "GirSomnath",
  "Jamnagar", "Junagadh", "Kachchh", "Kheda", "Mahesana",
  "Mahisagar", "Morbi", "Narmada", "Navsari", "PanchMahals",
  "Patan", "Porbandar", "Rajkot", "SabarKantha", "Surat",
  "Surendranagar", "Tapi", "TheDangs", "Vadodara", "Valsad",
  "Ambala", "Bhiwani", "Faridabad", "Fatehabad", "Gurgaon",
  "Hisar", "Jhajjar", "Jind", "Kaithal", "Karnal",
  "Kurukshetra", "Mahendragarh", "Mewat", "Palwal", "Panchkula",
  "Panipat", "Rewari", "Rohtak", "Sirsa", "Sonipat",
  "Yamunanagar", "Chamba", "Hamirpur", "Kangra", "Kinnaur",
  "Kullu", "Lahul&Spiti", "Mandi", "Shimla", "Sirmaur",
  "Solan", "Una", "Anantnag", "Badgam", "Bandipore",
  "Baramulla", "Doda", "Ganderbal", "Jammu", "Kargil",
  "Kathua", "Kishtwar", "Kulgam", "Kupwara", "Leh(Ladakh)",
  "Poonch", "Pulwama", "Rajouri", "Ramban", "Reasi",
  "Samba", "Shupiyan", "Srinagar", "Udhampur", "Bokaro",
  "Chatra", "Deoghar", "Dhanbad", "Dumka", "Garhwa",
  "Giridih", "Godda", "Gumla", "Hazaribagh", "Jamtara",
  "Khunti", "Kodarma", "Latehar", "Lohardaga", "Pakur",
  "Palamu", "PashchimiSinghbhum", "PurbiSinghbhum", "Ramgarh", "Ranchi",
  "Sahibganj", "Saraikela-kharsawan", "Simdega", "Bagalkot", "Bangalore",
  "BangaloreRural", "Belgaum", "Bellary", "Bidar", "Chamrajnagar",
  "Chikballapura", "Chikmagalur", "Chitradurga", "DakshinaKannada", "Davanagere",
  "Dharwad", "Gadag", "Gulbarga", "Hassan", "Haveri",
  "Kodagu", "Kolar", "Koppal", "Mandya", "Mysore",
  "Raichur", "Ramanagara", "Shimoga", "Tumkur", "Udupi",
  "UttaraKannada", "Yadgir", "Alappuzha", "Ernakulam", "Idukki",
  "Kannur", "Kasaragod", "Kollam", "Kottayam", "Kozhikode",
  "Malappuram", "Palakkad", "Pathanamthitta", "Thiruvananthapuram", "Thrissur",
  "Wayanad", "Lakshadweep", "AgarMalwa", "Alirajpur", "Anuppur",
  "Ashoknagar", "Balaghat", "Barwani", "Betul", "Bhind",
  "Bhopal", "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh",
  "Datia", "Dewas", "Dhar", "Dindori", "EastNimar",
  "Guna", "Gwalior", "Harda", "Hoshangabad", "Indore",
  "Jabalpur", "Jhabua", "Katni", "Mandla", "Mandsaur",
  "Morena", "Narsimhapur", "Neemuch", "Panna", "Raisen",
  "Rajgarh", "Ratlam", "Rewa", "Sagar", "Satna",
  "Sehore", "Seoni", "Shahdol", "Shajapur", "Sheopur",
  "Shivpuri", "Sidhi", "Singrauli", "Tikamgarh", "Ujjain",
  "Umaria", "Vidisha", "WestNimar", "Ahmadnagar", "Akola",
  "Amravati", "Bhandara", "Bid", "Buldana", "Chandrapur",
  "Dhule", "Garhchiroli", "Gondiya", "Hingoli", "Jalgaon",
  "Jalna", "Kolhapur", "Latur", "MumbaiCity", "MumbaiSuburban",
  "Nagpur", "Nanded", "Nandurbar", "Nashik", "Osmanabad",
  "Palghar", "Parbhani", "Pune", "Ratnagiri", "Sangli",
  "Satara", "Sindhudurg", "Solapur", "Thane", "Wardha",
  "Washim", "Yavatmal", "Bishnupur", "Chandel", "Churachandpur",
  "ImphalEast", "ImphalWest", "Senapati", "Tamenglong", "Thoubal",
  "Ukhrul", "EastGaroHills", "EastKhasiHills", "JaintiaHills", "NorthGaroHills",
  "RiBhoi", "SouthGaroHills", "SouthWestGaroHills", "SouthWestKhasiHills", "WestGaroHills",
  "WestKhasiHills", "Aizawl", "Champhai", "Kolasib", "Lawangtlai",
  "Lunglei", "Mamit", "Saiha", "Serchhip", "Dimapur",
  "Kiphire", "Kohima", "Longleng", "Mokokchung", "Mon",
  "Peren", "Phek", "Tuensang", "Wokha", "Zunheboto",
  "West", "Anugul", "Balangir", "Baleshwar", "Bargarh",
  "Bauda", "Bhadrak", "Cuttack", "Debagarh", "Dhenkanal",
  "Gajapati", "Ganjam", "Jagatsinghapur", "Jajapur", "Jharsuguda",
  "Kalahandi", "Kandhamal", "Kendrapara", "Kendujhar", "Khordha",
  "Koraput", "Malkangiri", "Mayurbhanj", "Nabarangapur", "Nayagarh",
  "Nuapada", "Puri", "Rayagada", "Sambalpur", "Subarnapur",
  "Sundargarh", "Karaikal", "Mahe", "Puducherry", "Yanam",
  "Amritsar", "Barnala", "Bathinda", "Faridkot", "FatehgarhSahib",
  "Fazilka", "Firozpur", "Gurdaspur", "Hoshiarpur", "Jalandhar",
  "Kapurthala", "Ludhiana", "Mansa", "Moga", "Muktsar",
  "Pathankot", "Patiala", "Rupnagar", "SahibzadaAjitSinghNagar", "Sangrur",
  "ShahidBhagatSinghNagar", "TarnTaran", "Ajmer", "Alwar", "Banswara",
  "Baran", "Barmer", "Bharatpur", "Bhilwara", "Bikaner",
  "Bundi", "Chittaurgarh", "Churu", "Dausa", "Dhaulpur",
  "Dungarpur", "Ganganagar", "Hanumangarh", "Jaipur", "Jaisalmer",
  "Jalor", "Jhalawar", "Jhunjhunun", "Jodhpur", "Karauli",
  "Kota", "Nagaur", "Pali", "Pratapgarh", "Rajsamand",
  "SawaiMadhopur", "Sikar", "Sirohi", "Tonk", "Udaipur",
  "EastSikkim", "NorthSikkim", "SouthSikkim", "WestSikkim", "Ariyalur",
  "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri", "Dindigul",
  "Erode", "Kancheepuram", "Kanniyakumari", "Karur", "Krishnagiri",
  "Madurai", "Nagappattinam", "Namakkal", "Perambalur", "Pudukkottai",
  "Ramanathapuram", "Salem", "Sivaganga", "Thanjavur", "TheNilgiris",
  "Theni", "Thiruvallur", "Thiruvarur", "Thoothukkudi", "Tiruchirappalli",
  "Tirunelveli", "Tiruppur", "Tiruvannamalai", "Vellore", "Viluppuram",
  "Virudunagar", "Adilabad", "Hyderabad", "Karimnagar", "Khammam",
  "Mahbubnagar", "Medak", "Nalgonda", "Nizamabad", "RangaReddy",
  "Warangal", "Dhalai", "Gomati", "Khowai", "NorthTripura",
  "Sipahijala", "SouthTripura", "Unokoti", "WestTripura", "Agra",
  "Aligarh", "Allahabad", "AmbedkarNagar", "Amethi", "Amroha",
  "Auraiya", "Azamgarh", "Baghpat", "Bahraich", "Ballia",
  "Banda", "Barabanki", "Bareilly", "Basti", "Bijnor",
  "Budaun", "Bulandshahr", "Chandauli", "Chitrakoot", "Deoria",
  "Etah", "Etawah", "Faizabad", "Farrukhabad", "Fatehpur",
  "Firozabad", "GautamBuddhaNagar", "Ghaziabad", "Ghazipur", "Gonda",
  "Gorakhpur", "Hapur", "Hardoi", "Hathras", "Jalaun",
  "Jaunpur", "Jhansi", "Kannauj", "KanpurDehat", "KanpurNagar",
  "Kasganj", "Kaushambi", "Kushinagar", "LakhimpurKheri", "Lalitpur",
  "Lucknow", "Maharajganj", "Mahoba", "Mainpuri", "Mathura",
  "Mau", "Meerut", "Mirzapur", "Moradabad", "Muzaffarnagar",
  "Pilibhit", "RaeBareli", "Rampur", "Saharanpur", "Sambhal",
  "SantKabirNagar", "SantRaviDasNagar", "Shahjahanpur", "Shamli", "Shravasti",
  "SiddharthNagar", "Sitapur", "Sonbhadra", "Sultanpur", "Unnao",
  "Varanasi", "Almora", "Bageshwar", "Chamoli", "Champawat",
  "Dehradun", "Garhwal", "Hardwar", "Nainital", "Pithoragarh",
  "Rudraprayag", "TehriGarhwal", "UdhamSinghNagar", "Uttarkashi", "Alipurduar",
  "Bankura", "Barddhaman", "Birbhum", "DakshinDinajpur", "Darjiling",
  "Haora", "Hugli", "Jalpaiguri", "KochBihar", "Kolkata",
  "Maldah", "Murshidabad", "Nadia", "North24Parganas", "PashchimMedinipur",
  "PurbaMedinipur", "Puruliya", "South24Parganas", "UttarDinajpur"
)
```



```{r}
# Compare the vectors
same_length <- length(nfhs_district_names) == length(gadm_district_names)
same_length


common_districts <- intersect(nfhs_district_names, gadm_district_names)

# Print the common districts
print("Common Districts:")
print(common_districts)
```


```{r}
# Identify mismatched districts
nfhs_not_in_gadm <- setdiff(nfhs_district_names, gadm_district_names)
gadm_not_in_nfhs <- setdiff(gadm_district_names, nfhs_district_names)

# Print the results
cat("Number of districts in NFHS not in GADM: ", length(nfhs_not_in_gadm), "\n")
cat("Number of districts in GADM not in NFHS: ", length(gadm_not_in_nfhs), "\n")
```


```{r}
# Install and load the stringdist package

library(stringdist)


# Perform fuzzy matching with a threshold for string similarity
fuzzy_matches <- sapply(nfhs_not_in_gadm, function(x) {
  match <- amatch(x, gadm_not_in_nfhs, maxDist = 2) # Adjust maxDist as needed
  if (!is.na(match)) {
    return(c(NFHS = x, GADM = gadm_not_in_nfhs[match]))
  } else {
    return(NULL)
  }
})

# Filter out the NULL matches
fuzzy_matches <- do.call(rbind, fuzzy_matches)

# Print the fuzzy matches
print("Potential fuzzy matches between NFHS and GADM:")
print(fuzzy_matches)

```

```{r}
# Create a dictionary for mapping GADM district names to NFHS district names
gadm_to_nfhs_map <- list(
  "Poonch" = "Punch",
  "Baramulla" = "Baramula",
  "Lahul&Spiti" = "Lahul & Spiti",
  "FatehgarhSahib" = "Fatehgarh Sahib",
  "TarnTaran" = "Tarn Taran",
  "TehriGarhwal" = "Tehri Garhwal",
  "UdhamSinghNagar" = "Udham Singh Nagar",
  "SawaiMadhopur" = "Sawai Madhopur",
  "GautamBuddhaNagar" = "Gautam Buddha Nagar",
  "KanpurDehat" = "Kanpur Dehat",
  "KanpurNagar" = "Kanpur Nagar",
  "Barabanki" = "Bara Banki",
  "AmbedkarNagar" = "Ambedkar Nagar",
  "Shravasti" = "Shrawasti",
  "SiddharthNagar" = "Siddharthnagar",
  "SantKabirNagar" = "Sant Kabir Nagar",
  "Maharajganj" = "Mahrajganj",
  "PashchimChamparan" = "Pashchim Champaran",
  "PurbaChamparan" = "Purba Champaran",
  "WestKameng" = "West Kameng",
  "EastKameng" = "East Kameng",
  "PapumPare" = "Papum Pare",
  "UpperSubansiri" = "Upper Subansiri",
  "UpperSiang" = "Upper Siang",
  "LowerSubansiri" = "Lower Subansiri",
  "DibangValley" = "Dibang Valley",
  "LowerDibangValley" = "Lower Dibang Valley",
  "ImphalWest" = "Imphal West",
  "ImphalEast" = "Imphal East",
  "Lawangtlai" = "Lawngtlai",
  "SouthGaroHills" = "South Garo Hills",
  "RiBhoi" = "Ribhoi",
  "EastKhasiHills" = "East Khasi Hills",
  "DimaHasao" = "Dima Hasao",
  "KamrupMetropolitan" = "Kamrup Metropolitan",
  "KochBihar" = "Koch Bihar",
  "UttarDinajpur" = "Uttar Dinajpur",
  "DakshinDinajpur" = "Dakshin Dinajpur",
  "PashchimMedinipur" = "Paschim Medinipur",
  "PurbaMedinipur" = "Purba Medinipur",
  "PurbiSinghbhum" = "Purbi Singhbhum",
  "PashchimiSinghbhum" = "Pashchimi Singhbhum",
  "Saraikela-kharsawan" = "Saraikela-Kharsawan",
  "Bauda" = "Baudh",
  "Janjgir-Champa" = "Janjgir - Champa",
  "UttarBastarKanker" = "Uttar Bastar Kanker",
  "BanasKantha" = "Banas Kantha",
  "Dahod" = "Dohad",
  "TheDangs" = "The Dangs",
  "Garhchiroli" = "Gadchiroli",
  "MumbaiSuburban" = "Mumbai Suburban",
  "EastGodavari" = "East Godavari",
  "WestGodavari" = "West Godavari",
  "UttaraKannada" = "Uttara Kannada",
  "DakshinaKannada" = "Dakshina Kannada",
  "Chamrajnagar" = "Chamarajanagar",
  "Chikballapura" = "Chikkaballapura",
  "BangaloreRural" = "Bangalore Rural",
  "NorthGoa" = "North Goa",
  "SouthGoa" = "South Goa",
  "TheNilgiris" = "The Nilgiris",
  "Nagappattinam" = "Nagapattinam",
  "Virudunagar" = "Virudhunagar",
  "SouthAndaman" = "South Andaman",
  "EastSiang" = "East Siang",
  "KurungKumey" = "Kurung Kumey",
  "WestSiang" = "West Siang",
  "KarbiAnglong" = "Karbi Anglong",
  "BalodaBazar" = "Baloda Bazar",
  "Gariaband" = "Gariyaband",
  "Kondagaon" = "Kodagaon",
  "Aravalli" = "Aravali",
  "ChhotaUdaipur" = "Chhota Udaipur",
  "DevbhumiDwarka" = "Devbhumi Dwarka",
  "GirSomnath" = "Gir Somnath",
  "PanchMahals" = "Panch Mahals",
  "SabarKantha" = "Sabar Kantha",
  "AgarMalwa" = "Agar Malwa",
  "EastGaroHills" = "East Garo Hills",
  "NorthGaroHills" = "North Garo Hills",
  "WestGaroHills" = "West Garo Hills",
  "WestKhasiHills" = "West Khasi Hills",
  "Mahbubnagar" = "Mahabubnagar",
  "RangaReddy" = "Ranga Reddy",
  "NorthTripura" = "North Tripura",
  "Sipahijala" = "Sepahijala",
  "SouthTripura" = "South Tripura",
  "Unokoti" = "Unakoti",
  "WestTripura" = "West Tripura",
  "RaeBareli" = "Rae Bareli",
  "ShahidBhagatSinghNagar" = "Shahid Bhagat Singh Nagar",
  "SahibzadaAjitSinghNagar" = "Sahibzada Ajit Singh Nagar",
  "LakhimpurKheri" = "Kheri",
  "DadraandNagarHaveli" = "Dadra & Nagar Haveli",
  "MumbaiCity" = "Mumbai",
  "NorthandMiddleAndaman" = "North & Middle Andaman",
  "NicobarIslands" = "Nicobars",
  "Nellore" = "Sri Potti Sriramulu Nellore",
  "North24Parganas" = "North Twenty Four Parganas",
  "South24Parganas" = "South Twenty Four Parganas",
  "Barddhaman" = "Purba Barddhaman",
  "EastNimar" = "Khandwa (East Nimar)",
  "Kaimur" = "Kaimur (Bhabua)",
  "WestNimar" = "Khargone (West Nimar)",
  "JaintiaHills" = "East Jantia Hills",
  "SouthWestGaroHills" = "South West Garo Hills",
  "SantRaviDasNagar" = "Sant Ravidas Nagar (Bhadohi)",
  "Hathras" = "Mahamaya Nagar",
  "Kasganj" = "Kanshiram Nagar",
  "Warangal" = "Warangal Rural",
  "Amroha" = "Jyotiba Phule Nagar",
  "NorthSikkim" = "North District",
  "SouthSikkim" = "South District",
  "EastSikkim" = "East District",
  "WestSikkim" = "West District",
  "SouthWestKhasiHills" = "South West Khasi Hills"
)

# Convert to a named vector for easier replacement
gadm_to_nfhs_map <- unlist(gadm_to_nfhs_map)

# Update the Names_2 column
india_districts <- india_districts %>%
  mutate(NAME_2 = ifelse(NAME_2 %in% names(gadm_to_nfhs_map), gadm_to_nfhs_map[NAME_2], NAME_2))

# Print the updated names for verification
print("Updated NAME_2 column:")
print(india_districts$NAME_2)

```
```{r}
# Load the writexl package
library(writexl)

# Convert the spatial data frame to a regular data frame if needed
india_districts_df <- as.data.frame(india_districts)

# Write the data frame to an Excel file
write_xlsx(india_districts_df, "updated_india_districts.xlsx")
```








```{r}
# Assuming nfhs_district_names and india_districts are already defined and updated

# Extract the updated district names from the spatial dataset
gadm_district_names_updated <- india_districts$NAME_2

# Find the districts in NFHS not in GADM
nfhs_not_in_gadm <- setdiff(nfhs_district_names, gadm_district_names_updated)

# Find the districts in GADM not in NFHS
gadm_not_in_nfhs <- setdiff(gadm_district_names_updated, nfhs_district_names)

# Print the results
cat("Number of districts in NFHS not in GADM: ", length(nfhs_not_in_gadm), "\n")
cat("Number of districts in GADM not in NFHS: ", length(gadm_not_in_nfhs), "\n")
```


```{r}
# Optional: Print the names of the districts
cat("Districts in NFHS not in GADM: ", nfhs_not_in_gadm, "\n")
```


```{r}
cat("Districts in GADM not in NFHS: ", gadm_not_in_nfhs, "\n")

```

```{r}
length(india_districts$NAME_2)
```

```{r}
# Load necessary libraries
library(dplyr)
library(ggplot2)
library(sf)

# Filter the spatial data for Kerala
kerala_districts <- india_districts %>% 
  filter(NAME_1 == "Kerala")

# Define the mapping for Kerala districts
kerala_mapping <- data.frame(
  sdist = c(588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601),
  district_name = c("Kasaragod", "Kannur", "Wayanad", "Kozhikode", "Malappuram", 
                    "Palakkad", "Thrissur", "Ernakulam", "Idukki", "Kottayam", 
                    "Alappuzha", "Pathanamthitta", "Kollam", "Thiruvananthapuram"),
  stringsAsFactors = FALSE
)

# Filter the prevalence data for Kerala
kerala_prevalence <- district_prevalence_true %>% 
  filter(sdist %in% kerala_mapping$sdist) %>%
  left_join(kerala_mapping, by = "sdist") %>%
  select(district_name, `I(m19 < 2500)TRUE`) %>%
  rename(prevalence = `I(m19 < 2500)TRUE`)

# Join the spatial data with the prevalence data
kerala_districts <- kerala_districts %>% 
  left_join(kerala_prevalence, by = c("NAME_2" = "district_name"))

# Plot the map
ggplot(kerala_districts) +
  geom_sf(aes(fill = prevalence)) +
  scale_fill_viridis_c() +
  labs(title = "Low Birth Weight Prevalence in Kerala",
       fill = "Prevalence (%)") +
  theme_minimal()



# Filter the spatial data for Andaman and Nicobar
andaman_districts <- india_districts %>% 
  filter(NAME_1 == "AndamanandNicobar")

# Define the mapping for Andaman and Nicobar districts
andaman_mapping <- data.frame(
  sdist = c(638, 639, 640),
  district_name = c("Nicobars", "North & Middle Andaman", "South Andaman"),
  stringsAsFactors = FALSE
)

# Filter the prevalence data for Andaman and Nicobar
andaman_prevalence <- district_prevalence_true %>% 
  filter(sdist %in% andaman_mapping$sdist) %>%
  left_join(andaman_mapping, by = "sdist") %>%
  select(district_name, `I(m19 < 2500)TRUE`) %>%
  rename(prevalence = `I(m19 < 2500)TRUE`)

# Join the spatial data with the prevalence data
andaman_districts <- andaman_districts %>% 
  left_join(andaman_prevalence, by = c("NAME_2" = "district_name"))

# Plot the map
ggplot(andaman_districts) +
  geom_sf(aes(fill = prevalence)) +
  scale_fill_viridis_c() +
  labs(title = "Low Birth Weight Prevalence in Andaman and Nicobar",
       fill = "Prevalence (%)") +
  theme_minimal()




# Filter the spatial data for Andhra Pradesh
andhra_districts <- india_districts %>% 
  filter(NAME_1 == "AndhraPradesh")

# Define the mapping for Andhra Pradesh districts
andhra_mapping <- data.frame(
  sdist = c(542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554),
  district_name = c("Srikakulam", "Vizianagaram", "Visakhapatnam", "East Godavari", 
                    "West Godavari", "Krishna", "Guntur", "Prakasam", 
                    "Sri Potti Sriramulu Nellore", "Y.S.R.", "Kurnool", "Anantapur", "Chittoor"),
  stringsAsFactors = FALSE
)

# Filter the prevalence data for Andhra Pradesh
andhra_prevalence <- district_prevalence_true %>% 
  filter(sdist %in% andhra_mapping$sdist) %>%
  left_join(andhra_mapping, by = "sdist") %>%
  select(district_name, `I(m19 < 2500)TRUE`) %>%
  rename(prevalence = `I(m19 < 2500)TRUE`)

# Join the spatial data with the prevalence data
andhra_districts <- andhra_districts %>% 
  left_join(andhra_prevalence, by = c("NAME_2" = "district_name"))

# Plot the choropleth map
ggplot(andhra_districts) +
  geom_sf(aes(fill = prevalence)) +
  scale_fill_viridis_c() +
  labs(title = "Low Birth Weight Prevalence by District in Andhra Pradesh",
       fill = "Prevalence (%)") +
  theme_minimal()




# Filter the spatial data for Arunachal Pradesh
arunachal_districts <- india_districts %>% 
  filter(NAME_1 == "ArunachalPradesh")

# Define the mapping for Arunachal Pradesh districts
arunachal_mapping <- data.frame(
  sdist = c(245, 246, 247, 248, 249, 252, 801, 802, 803, 804, 805, 806, 808, 809),
  district_name = c("Tawang", "West Kameng", "East Kameng", "Papum Pare", 
                    "Upper Subansiri", "Upper Siang", "East Siang", "Kra Daadi", 
                    "Kurung Kumey", "Lohit", "Longding", "Namsai", 
                    "Tirap", "West Siang"),
  stringsAsFactors = FALSE
)

# Filter the prevalence data for Arunachal Pradesh
arunachal_prevalence <- district_prevalence_true %>% 
  filter(sdist %in% arunachal_mapping$sdist) %>%
  left_join(arunachal_mapping, by = "sdist") %>%
  select(district_name, `I(m19 < 2500)TRUE`) %>%
  rename(prevalence = `I(m19 < 2500)TRUE`)

# Join the spatial data with the prevalence data
arunachal_districts <- arunachal_districts %>% 
  left_join(arunachal_prevalence, by = c("NAME_2" = "district_name"))

# Plot the choropleth map
ggplot(arunachal_districts) +
  geom_sf(aes(fill = prevalence)) +
  scale_fill_viridis_c() +
  labs(title = "Low Birth Weight Prevalence in Arunachal Pradesh",
       fill = "Prevalence (%)") +
  theme_minimal()


# Filter the spatial data for Goa
goa_districts <- india_districts %>% 
  filter(NAME_1 == "Goa")

# Define the mapping for Goa districts
goa_mapping <- data.frame(
  sdist = c(585, 586),
  district_name = c("North Goa", "South Goa"),
  stringsAsFactors = FALSE
)

# Filter the prevalence data for Goa
goa_prevalence <- district_prevalence_true %>% 
  filter(sdist %in% goa_mapping$sdist) %>%
  left_join(goa_mapping, by = "sdist") %>%
  select(district_name, `I(m19 < 2500)TRUE`) %>%
  rename(prevalence = `I(m19 < 2500)TRUE`)

# Join the spatial data with the prevalence data
goa_districts <- goa_districts %>% 
  left_join(goa_prevalence, by = c("NAME_2" = "district_name"))

# Plot the choropleth map
ggplot(goa_districts) +
  geom_sf(aes(fill = prevalence)) +
  scale_fill_viridis_c() +
  labs(title = "Low Birth Weight Prevalence by District in Goa",
       fill = "Prevalence (%)") +
  theme_minimal()



```

```{r}


# Filter the spatial data for West Bengal
west_bengal_districts <- india_districts %>% 
  filter(NAME_1 == "WestBengal")

# Define the mapping for West Bengal districts
west_bengal_mapping <- data.frame(
  sdist = c(932, 327, 328, 329, 330, 331, 332, 333, 334, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345),
  district_name = c("Purba Barddhaman", "Darjiling", "Jalpaiguri", "Koch Bihar", "Uttar Dinajpur", 
                    "Dakshin Dinajpur", "Maldah", "Murshidabad", "Birbhum", "Nadia", 
                    "North Twenty Four Parganas", "Hugli", "Bankura", "Puruliya", 
                    "Haora", "Kolkata", "South Twenty Four Parganas", 
                    "Paschim Medinipur", "Purba Medinipur"),
  stringsAsFactors = FALSE
)

# Filter the prevalence data for West Bengal
west_bengal_prevalence <- district_prevalence_true %>% 
  filter(sdist %in% west_bengal_mapping$sdist) %>%
  left_join(west_bengal_mapping, by = "sdist") %>%
  select(district_name, `I(m19 < 2500)TRUE`) %>%
  rename(prevalence = `I(m19 < 2500)TRUE`)

# Join the spatial data with the prevalence data
west_bengal_districts <- west_bengal_districts %>% 
  left_join(west_bengal_prevalence, by = c("NAME_2" = "district_name"))

# Plot the choropleth map
ggplot(west_bengal_districts) +
  geom_sf(aes(fill = prevalence)) +
  scale_fill_viridis_c() +
  labs(title = "Low Birth Weight Prevalence in West Bengal",
       fill = "Prevalence (%)") +
  theme_minimal()





# Filter the spatial data for Assam
assam_districts <- india_districts %>% 
  filter(NAME_1 == "Assam")

# Define the mapping for Assam districts
assam_mapping <- data.frame(
  sdist = c(812, 814, 815, 817, 818, 819, 300, 302, 303, 304, 307, 308, 309, 310, 313, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326),
  district_name = c("Dhubri", "Jorhat", "Karbi Anglong", "Nagaon", "Sivasagar", "Sonitpur", 
                    "Kokrajhar", "Goalpara", "Barpeta", "Morigaon", "Lakhimpur", "Dhemaji", 
                    "Tinsukia", "Dibrugarh", "Golaghat", "Dima Hasao", "Cachar", "Karimganj", 
                    "Hailakandi", "Bongaigaon", "Chirang", "Kamrup", "Kamrup Metropolitan", 
                    "Nalbari", "Baksa", "Darrang", "Udalguri"),
  stringsAsFactors = FALSE
)

# Filter the prevalence data for Assam
assam_prevalence <- district_prevalence_true %>% 
  filter(sdist %in% assam_mapping$sdist) %>%
  left_join(assam_mapping, by = "sdist") %>%
  select(district_name, `I(m19 < 2500)TRUE`) %>%
  rename(prevalence = `I(m19 < 2500)TRUE`)

# Join the spatial data with the prevalence data
assam_districts <- assam_districts %>% 
  left_join(assam_prevalence, by = c("NAME_2" = "district_name"))

# Plot the choropleth map
ggplot(assam_districts) +
  geom_sf(aes(fill = prevalence)) +
  scale_fill_viridis_c() +
  labs(title = "Low Birth Weight Prevalence  in Assam",
       fill = "Prevalence (%)") +
  theme_minimal()



# Filter the spatial data for Himachal Pradesh
hp_districts <- india_districts %>%
  filter(NAME_1 == "HimachalPradesh")

# Handle duplicate entries for Lahul & Spiti and Kinnaur by merging their geometries
hp_districts <- hp_districts %>%
  group_by(NAME_2) %>%
  summarize(geometry = st_union(geometry))

# Define the mapping for Himachal Pradesh districts
hp_mapping <- data.frame(
  sdist = c(23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34),
  district_name = c("Chamba", "Kangra", "Lahul & Spiti", "Kullu", "Mandi", "Hamirpur", "Una",
                    "Bilaspur", "Solan", "Sirmaur", "Shimla", "Kinnaur"),
  stringsAsFactors = FALSE
)

# Filter the prevalence data for Himachal Pradesh
hp_prevalence <- district_prevalence_true %>%
  filter(sdist %in% hp_mapping$sdist) %>%
  left_join(hp_mapping, by = "sdist") %>%
  select(district_name, `I(m19 < 2500)TRUE`) %>%
  rename(prevalence = `I(m19 < 2500)TRUE`)

# Join the spatial data with the prevalence data
hp_districts <- hp_districts %>%
  left_join(hp_prevalence, by = c("NAME_2" = "district_name"))

# Plot the choropleth map
ggplot(hp_districts) +
  geom_sf(aes(fill = prevalence)) +
  scale_fill_viridis_c() +
  labs(title = "Low Birth Weight Prevalence by District in Himachal Pradesh",
       fill = "Prevalence (%)") +
  theme_minimal()


# Filter the spatial data for Lakshadweep
lakshadweep_districts <- india_districts %>%
  filter(NAME_1 == "Lakshadweep")

# Define the mapping for Lakshadweep districts
lakshadweep_mapping <- data.frame(
  sdist = 587,
  district_name = "Lakshadweep",
  stringsAsFactors = FALSE
)

# Filter the prevalence data for Lakshadweep
lakshadweep_prevalence <- district_prevalence_true %>%
  filter(sdist == 587) %>%
  left_join(lakshadweep_mapping, by = "sdist") %>%
  select(district_name, `I(m19 < 2500)TRUE`) %>%
  rename(prevalence = `I(m19 < 2500)TRUE`)

# Join the spatial data with the prevalence data
lakshadweep_districts <- lakshadweep_districts %>%
  left_join(lakshadweep_prevalence, by = c("NAME_2" = "district_name"))

# Plot the choropleth map
ggplot(lakshadweep_districts) +
  geom_sf(aes(fill = prevalence)) +
  scale_fill_viridis_c() +
  labs(title = "Low Birth Weight Prevalence in Lakshadweep",
       fill = "Prevalence (%)") +
  theme_minimal()


```






















































```{r}
unique_states <- unique(india_states$NAME_1)
print(unique_states)
```



```{r}
# Created a mapping for the state names
state_mapping <- data.frame(
  v024 = c(1:24, 25, 25, 27:36),
  state_name = c("JammuandKashmir", "HimachalPradesh", "Punjab", "Chandigarh", 
                 "Uttarakhand", "Haryana", "NCTofDelhi", "Rajasthan", "UttarPradesh", 
                 "Bihar", "Sikkim", "ArunachalPradesh", "Nagaland", "Manipur", 
                 "Mizoram", "Tripura", "Meghalaya", "Assam", "WestBengal", "Jharkhand", 
                 "Odisha", "Chhattisgarh", "MadhyaPradesh", "Gujarat", 
                 "DadraandNagarHaveliandDamanandDiu", "DadraandNagarHaveliandDamanandDiu", "Maharashtra", "AndhraPradesh", 
                 "Karnataka", "Goa", "Lakshadweep", "Kerala", "TamilNadu", 
                 "Puducherry", "AndamanandNicobar", "Telangana"),
  stringsAsFactors = FALSE
)

# Combining Dadra and Nagar Haveli and Daman and Diu in the prevalence data because this is mentioned as one state in the NFHS dataset and as seperate in the GADM file
state_prevalence_true <- state_prevalence_true %>%
  mutate(v024 = ifelse(v024 == 25, 25, v024))

# Join this mapping to the prevalence_by_state data
state_prevalence_true <- state_prevalence_true %>%
  left_join(state_mapping, by = "v024") %>%
  select(state_name, `I(m19 < 2500)TRUE`, `se.I(m19 < 2500)TRUE`) %>%
  rename(prevalence = `I(m19 < 2500)TRUE`, se = `se.I(m19 < 2500)TRUE`)

# Combined Dadra and Nagar Haveli and Daman and Diu in the spatial data
india_states <- india_states %>%
  mutate(NAME_1 = ifelse(NAME_1 %in% c("DadraandNagarHaveli", "DamanandDiu"), "DadraandNagarHaveliandDamanandDiu", NAME_1))

# Combine prevalence data for Dadra and Nagar Haveli and Daman and Diu
state_prevalence_true <- state_prevalence_true %>%
  group_by(state_name) %>%
  summarize(prevalence = mean(prevalence, na.rm = TRUE), se = mean(se, na.rm = TRUE))

# Join the standardized state names with the spatial data
india_states <- india_states %>%
  left_join(state_prevalence_true, by = c("NAME_1" = "state_name"))

# Removed Ladakh from the dataset because Ladakh is not there in the NFHS data
india_states <- india_states %>%
  filter(NAME_1 != "Ladakh")

# Plot the map
ggplot(india_states) +
  geom_sf(aes(fill = prevalence)) +
  scale_fill_viridis_c() +
  labs(title = "Low Birth Weight Prevalence by State in India",
       fill = "Prevalence (%)") +
  theme_minimal()


```



















