---
title: "District level mapping and Fay Herriot Model"
author: "Teena Thomas"
date: "2024-02-22"
output: word_document
---


## Cleaning the district shape file to match the district names between the json file and NFHS 


```{r}
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(dplyr)
library(sf)
library(ggplot2)
```


```{r}
india_districts <- st_read("gadm41_IND_2.json")
head(india_districts)
```


```{r}
unique(india_districts$NAME_2)
```


```{r}
# Create a vector with all the district names
nfhs_district_names <- c(
  "Kupwara", "Badgam", "Leh(Ladakh)", "Kargil", "Punch", "Rajouri", "Kathua", "Baramula", "Bandipore", "Srinagar", 
  "Ganderbal", "Pulwama", "Shupiyan", "Anantnag", "Kulgam", "Doda", "Ramban", "Kishtwar", "Udhampur", "Reasi", 
  "Jammu", "Samba", "Chamba", "Kangra", "Lahul & Spiti", "Kullu", "Mandi", "Hamirpur", "Una", "Bilaspur", 
  "Solan", "Sirmaur", "Shimla", "Kinnaur", "Kapurthala", "Jalandhar", "Hoshiarpur", "Shahid Bhagat Singh Nagar", 
  "Fatehgarh Sahib", "Ludhiana", "Moga", "Muktsar", "Faridkot", "Bathinda", "Mansa", "Patiala", "Amritsar", 
  "Tarn Taran", "Rupnagar", "Sahibzada Ajit Singh Nagar", "Sangrur", "Barnala", "Chandigarh", "Uttarkashi", 
  "Chamoli", "Rudraprayag", "Tehri Garhwal", "Dehradun", "Garhwal", "Pithoragarh", "Bageshwar", "Almora", 
  "Champawat", "Nainital", "Udham Singh Nagar", "Hardwar", "Panchkula", "Ambala", "Yamunanagar", "Kurukshetra", 
  "Kaithal", "Karnal", "Panipat", "Sonipat", "Jind", "Fatehabad", "Sirsa", "Hisar", "Rohtak", "Jhajjar", 
  "Mahendragarh", "Rewari", "Gurgaon", "Mewat", "Faridabad", "Palwal", "Ganganagar", "Hanumangarh", "Bikaner", 
  "Churu", "Jhunjhunun", "Alwar", "Bharatpur", "Dhaulpur", "Karauli", "Sawai Madhopur", "Dausa", "Jaipur", 
  "Sikar", "Nagaur", "Jodhpur", "Jaisalmer", "Barmer", "Jalor", "Sirohi", "Pali", "Ajmer", "Tonk", "Bundi", 
  "Bhilwara", "Rajsamand", "Dungarpur", "Banswara", "Chittaurgarh", "Kota", "Baran", "Jhalawar", "Udaipur", 
  "Pratapgarh", "Saharanpur", "Bijnor", "Rampur", "Jyotiba Phule Nagar", "Meerut", "Baghpat", "Gautam Buddha Nagar", 
  "Bulandshahr", "Aligarh", "Mahamaya Nagar", "Mathura", "Agra", "Firozabad", "Mainpuri", "Bareilly", "Pilibhit", 
  "Shahjahanpur", "Kheri", "Sitapur", "Hardoi", "Unnao", "Lucknow", "Farrukhabad", "Kannauj", "Etawah", "Auraiya", 
  "Kanpur Dehat", "Kanpur Nagar", "Jalaun", "Jhansi", "Lalitpur", "Hamirpur", "Mahoba", "Banda", "Chitrakoot", 
  "Fatehpur", "Pratapgarh", "Kaushambi", "Allahabad", "Bara Banki", "Faizabad", "Ambedkar Nagar", "Bahraich", 
  "Shrawasti", "Balrampur", "Gonda", "Siddharthnagar", "Basti", "Sant Kabir Nagar", "Mahrajganj", "Gorakhpur", 
  "Kushinagar", "Deoria", "Azamgarh", "Mau", "Ballia", "Jaunpur", "Ghazipur", "Chandauli", "Varanasi", 
  "Sant Ravidas Nagar (Bhadohi)", "Mirzapur", "Sonbhadra", "Etah", "Kanshiram Nagar", "Pashchim Champaran", 
  "Purba Champaran", "Sheohar", "Sitamarhi", "Madhubani", "Supaul", "Araria", "Kishanganj", "Purnia", 
  "Katihar", "Madhepura", "Saharsa", "Darbhanga", "Muzaffarpur", "Gopalganj", "Siwan", "Saran", "Vaishali", 
  "Samastipur", "Begusarai", "Khagaria", "Bhagalpur", "Banka", "Munger", "Lakhisarai", "Sheikhpura", "Nalanda", 
  "Patna", "Bhojpur", "Buxar", "Kaimur (Bhabua)", "Rohtas", "Aurangabad", "Gaya", "Nawada", "Jamui", "Jehanabad", 
  "Arwal", "North District", "West District", "South District", "East District", "Tawang", "West Kameng", 
  "East Kameng", "Papum Pare", "Upper Subansiri", "Upper Siang", "Changlang", "Lower Subansiri", "Dibang Valley", 
  "Lower Dibang Valley", "Anjaw", "Mon", "Mokokchung", "Zunheboto", "Wokha", "Dimapur", "Phek", "Tuensang", 
  "Longleng", "Kiphire", "Kohima", "Peren", "Senapati", "Tamenglong", "Churachandpur", "Bishnupur", "Thoubal", 
  "Imphal West", "Imphal East", "Ukhrul", "Chandel", "Mamit", "Kolasib", "Aizawl", "Champhai", "Serchhip", 
  "Lunglei", "Lawngtlai", "Saiha", "Dhalai", "South Garo Hills", "Ribhoi", "East Khasi Hills", "Kokrajhar", 
  "Goalpara", "Barpeta", "Morigaon", "Lakhimpur", "Dhemaji", "Tinsukia", "Dibrugarh", "Golaghat", "Dima Hasao", 
  "Cachar", "Karimganj", "Hailakandi", "Bongaigaon", "Chirang", "Kamrup", "Kamrup Metropolitan", "Nalbari", 
  "Baksa", "Darrang", "Udalguri", "Darjiling", "Jalpaiguri", "Koch Bihar", "Uttar Dinajpur", "Dakshin Dinajpur", 
  "Maldah", "Murshidabad", "Birbhum", "Nadia", "North Twenty Four Parganas", "Hugli", "Bankura", "Puruliya", 
  "Haora", "Kolkata", "South Twenty Four Parganas", "Paschim Medinipur", "Purba Medinipur", "Garhwa", "Chatra", 
  "Kodarma", "Giridih", "Deoghar", "Godda", "Sahibganj", "Pakur", "Dhanbad", "Bokaro", "Lohardaga", 
  "Purbi Singhbhum", "Palamu", "Latehar", "Hazaribagh", "Ramgarh", "Dumka", "Jamtara", "Ranchi", "Khunti", 
  "Gumla", "Simdega", "Pashchimi Singhbhum", "Saraikela-Kharsawan", "Bargarh", "Jharsuguda", "Sambalpur", 
  "Debagarh", "Sundargarh", "Kendujhar", "Mayurbhanj", "Baleshwar", "Bhadrak", "Kendrapara", "Jagatsinghapur", 
  "Cuttack", "Jajapur", "Dhenkanal", "Anugul", "Nayagarh", "Khordha", "Puri", "Ganjam", "Gajapati", 
  "Kandhamal", "Baudh", "Subarnapur", "Balangir", "Nuapada", "Kalahandi", "Rayagada", "Nabarangapur", 
  "Koraput", "Malkangiri", "Koriya", "Jashpur", "Raigarh", "Korba", "Janjgir - Champa", "Kabeerdham", 
  "Rajnandgaon", "Mahasamund", "Dhamtari", "Uttar Bastar Kanker", "Narayanpur", "Bijapur", "Sheopur", 
  "Morena", "Bhind", "Gwalior", "Datia", "Shivpuri", "Tikamgarh", "Chhatarpur", "Panna", "Sagar", "Damoh", 
  "Satna", "Rewa", "Umaria", "Neemuch", "Mandsaur", "Ratlam", "Ujjain", "Dewas", "Dhar", "Indore", 
  "Khargone (West Nimar)", "Barwani", "Rajgarh", "Vidisha", "Bhopal", "Sehore", "Raisen", "Betul", 
  "Harda", "Hoshangabad", "Katni", "Jabalpur", "Narsimhapur", "Dindori", "Mandla", "Chhindwara", "Seoni", 
  "Balaghat", "Guna", "Ashoknagar", "Shahdol", "Anuppur", "Sidhi", "Singrauli", "Jhabua", "Alirajpur", 
  "Khandwa (East Nimar)", "Burhanpur", "Kachchh", "Banas Kantha", "Patan", "Mahesana", "Gandhinagar", 
  "Porbandar", "Amreli", "Anand", "Dohad", "Narmada", "Bharuch", "The Dangs", "Navsari", "Valsad", "Surat", 
  "Tapi", "Diu", "Daman", "Dadra & Nagar Haveli", "Nandurbar", "Dhule", "Jalgaon", "Buldana", "Akola", 
  "Washim", "Amravati", "Wardha", "Nagpur", "Bhandara", "Gondiya", "Gadchiroli", "Chandrapur", "Yavatmal", 
  "Nanded", "Hingoli", "Parbhani", "Jalna", "Aurangabad", "Nashik", "Mumbai Suburban", "Mumbai", 
  "Raigarh", "Pune", "Ahmadnagar", "Bid", "Latur", "Osmanabad", "Solapur", "Satara", "Ratnagiri", 
  "Sindhudurg", "Kolhapur", "Sangli", "Srikakulam", "Vizianagaram", "Visakhapatnam", "East Godavari", 
  "West Godavari", "Krishna", "Guntur", "Prakasam", "Sri Potti Sriramulu Nellore", "Y.S.R.", "Kurnool", 
  "Anantapur", "Chittoor", "Belgaum", "Bagalkot", "Bijapur", "Bidar", "Raichur", "Koppal", "Gadag", 
  "Dharwad", "Uttara Kannada", "Haveri", "Bellary", "Chitradurga", "Davanagere", "Shimoga", "Udupi", 
  "Chikmagalur", "Tumkur", "Bangalore", "Mandya", "Hassan", "Dakshina Kannada", "Kodagu", "Mysore", 
  "Chamarajanagar", "Gulbarga", "Yadgir", "Kolar", "Chikkaballapura", "Bangalore Rural", "Ramanagara", 
  "North Goa", "South Goa", "Lakshadweep", "Kasaragod", "Kannur", "Wayanad", "Kozhikode", "Malappuram", 
  "Palakkad", "Thrissur", "Ernakulam", "Idukki", "Kottayam", "Alappuzha", "Pathanamthitta", "Kollam", 
  "Thiruvananthapuram", "Thiruvallur", "Chennai", "Kancheepuram", "Vellore", "Tiruvannamalai", "Viluppuram", 
  "Salem", "Namakkal", "Erode", "The Nilgiris", "Dindigul", "Karur", "Tiruchirappalli", "Perambalur", 
  "Ariyalur", "Cuddalore", "Nagapattinam", "Thiruvarur", "Thanjavur", "Pudukkottai", "Sivaganga", 
  "Madurai", "Theni", "Virudhunagar", "Ramanathapuram", "Thoothukkudi", "Tirunelveli", "Kanniyakumari", 
  "Dharmapuri", "Krishnagiri", "Coimbatore", "Tiruppur", "Yanam", "Puducherry", "Mahe", "Karaikal", 
  "Nicobars", "North & Middle Andaman", "South Andaman", "East Siang", "Kra Daadi", "Kurung Kumey", 
  "Lohit", "Longding", "Namsai", "Siang", "Tirap", "West Siang", "Biswanath", "Charaideo", "Dhubri", 
  "Hojai", "Jorhat", "Karbi Anglong", "Majuli", "Nagaon", "Sivasagar", "Sonitpur", "South Salmara Mancachar", 
  "West Karbi Anglong", "Balod", "Baloda Bazar", "Balrampur", "Bastar", "Bemetara", "Bilaspur", 
  "Dantewada", "Durg", "Gariyaband", "Kodagaon", "Mungeli", "Raipur", "Sukma", "Surajpur", "Surguja", 
  "Central", "East", "New Delhi", "North", "North East", "North West", "Shahdara", "South", "South East", 
  "South West", "West", "Ahmadabad", "Aravali", "Bhavnagar", "Botad", "Chhota Udaipur", "Devbhumi Dwarka", 
  "Gir Somnath", "Jamnagar", "Junagadh", "Kheda", "Mahisagar", "Morbi", "Panch Mahals", "Rajkot", 
  "Sabar Kantha", "Surendranagar", "Vadodara", "Bhiwani", "Charkhi Dadri", "Agar Malwa", "Shajapur", 
  "Palghar", "Thane", "East Garo Hills", "East Jantia Hills", "North Garo Hills", "South West Garo Hills", 
  "South West Khasi Hills", "West Garo Hills", "West Jaintia Hills", "West Khasi Hills", "Fazilka", 
  "Firozpur", "Gurdaspur", "Pathankot", "Adilabad", "Bhadradri Kothagudem", "Hyderabad", "Jagitial", 
  "Jangoan", "Jayashankar Bhupalapally", "Jogulamba Gadwal", "Kamareddy", "Karimnagar", "Khammam", 
  "Komaram Bheem Asifabad", "Mahabubabad", "Mahabubnagar", "Mancherial", "Medak", "Medchal-Malkajgiri", 
  "Nagarkurnool", "Nalgonda", "Nirmal", "Nizamabad", "Peddapalli", "Rajanna Sircilla", "Ranga Reddy", 
  "Sangareddy", "Siddipet", "Suryapet", "Vikarabad", "Wanaparthy", "Warangal Rural", "Warangal Urban", 
  "Yadadri Bhuvanagiri", "Gomati", "Khowai", "North Tripura", "Sepahijala", "South Tripura", "Unakoti", 
  "West Tripura", "Amethi", "Budaun", "Ghaziabad", "Hapur", "Moradabad", "Muzaffarnagar", "Rae Bareli", 
  "Sambhal", "Shamli", "Sultanpur", "Paschim Barddhaman", "Purba Barddhaman"
)

# Create a vector with all the district names
gadm_district_names <- c(
  "NicobarIslands", "NorthandMiddleAndaman", "SouthAndaman", "Anantapur", "Chittoor",
  "EastGodavari", "Guntur", "Krishna", "Kurnool", "Nellore",
  "Prakasam", "Srikakulam", "Visakhapatnam", "Vizianagaram", "WestGodavari",
  "Y.S.R.", "Anjaw", "Changlang", "DibangValley", "EastKameng",
  "EastSiang", "KurungKumey", "Lohit", "Longding", "LowerDibangValley",
  "LowerSubansiri", "Namsai", "PapumPare", "Tawang", "Tirap",
  "UpperSiang", "UpperSubansiri", "WestKameng", "WestSiang", "Baksa",
  "Barpeta", "Bongaigaon", "Cachar", "Chirang", "Darrang",
  "Dhemaji", "Dhubri", "Dibrugarh", "DimaHasao", "Goalpara",
  "Golaghat", "Hailakandi", "Jorhat", "Kamrup", "KamrupMetropolitan",
  "KarbiAnglong", "Karimganj", "Kokrajhar", "Lakhimpur", "Morigaon",
  "Nagaon", "Nalbari", "Sivasagar", "Sonitpur", "Tinsukia",
  "Udalguri", "Araria", "Arwal", "Aurangabad", "Banka",
  "Begusarai", "Bhagalpur", "Bhojpur", "Buxar", "Darbhanga",
  "Gaya", "Gopalganj", "Jamui", "Jehanabad", "Kaimur",
  "Katihar", "Khagaria", "Kishanganj", "Lakhisarai", "Madhepura",
  "Madhubani", "Munger", "Muzaffarpur", "Nalanda", "Nawada",
  "PashchimChamparan", "Patna", "PurbaChamparan", "Purnia", "Rohtas",
  "Saharsa", "Samastipur", "Saran", "Sheikhpura", "Sheohar",
  "Sitamarhi", "Siwan", "Supaul", "Vaishali", "Chandigarh",
  "Balod", "BalodaBazar", "Balrampur", "Bastar", "Bemetara",
  "Bijapur", "Bilaspur", "Dantewada", "Dhamtari", "Durg",
  "Gariaband", "Janjgir-Champa", "Jashpur", "Kabeerdham", "Kondagaon",
  "Korba", "Koriya", "Mahasamund", "Mungeli", "Narayanpur",
  "Raigarh", "Raipur", "Rajnandgaon", "Sukma", "Surajpur",
  "Surguja", "UttarBastarKanker", "DadraandNagarHaveli", "Daman", "Diu",
  "NorthGoa", "SouthGoa", "Ahmadabad", "Amreli", "Anand",
  "Aravalli", "BanasKantha", "Bharuch", "Bhavnagar", "Botad",
  "ChhotaUdaipur", "Dahod", "DevbhumiDwarka", "Gandhinagar", "GirSomnath",
  "Jamnagar", "Junagadh", "Kachchh", "Kheda", "Mahesana",
  "Mahisagar", "Morbi", "Narmada", "Navsari", "PanchMahals",
  "Patan", "Porbandar", "Rajkot", "SabarKantha", "Surat",
  "Surendranagar", "Tapi", "TheDangs", "Vadodara", "Valsad",
  "Ambala", "Bhiwani", "Faridabad", "Fatehabad", "Gurgaon",
  "Hisar", "Jhajjar", "Jind", "Kaithal", "Karnal",
  "Kurukshetra", "Mahendragarh", "Mewat", "Palwal", "Panchkula",
  "Panipat", "Rewari", "Rohtak", "Sirsa", "Sonipat",
  "Yamunanagar", "Chamba", "Hamirpur", "Kangra", "Kinnaur",
  "Kullu", "Lahul&Spiti", "Mandi", "Shimla", "Sirmaur",
  "Solan", "Una", "Anantnag", "Badgam", "Bandipore",
  "Baramulla", "Doda", "Ganderbal", "Jammu", "Kargil",
  "Kathua", "Kishtwar", "Kulgam", "Kupwara", "Leh(Ladakh)",
  "Poonch", "Pulwama", "Rajouri", "Ramban", "Reasi",
  "Samba", "Shupiyan", "Srinagar", "Udhampur", "Bokaro",
  "Chatra", "Deoghar", "Dhanbad", "Dumka", "Garhwa",
  "Giridih", "Godda", "Gumla", "Hazaribagh", "Jamtara",
  "Khunti", "Kodarma", "Latehar", "Lohardaga", "Pakur",
  "Palamu", "PashchimiSinghbhum", "PurbiSinghbhum", "Ramgarh", "Ranchi",
  "Sahibganj", "Saraikela-kharsawan", "Simdega", "Bagalkot", "Bangalore",
  "BangaloreRural", "Belgaum", "Bellary", "Bidar", "Chamrajnagar",
  "Chikballapura", "Chikmagalur", "Chitradurga", "DakshinaKannada", "Davanagere",
  "Dharwad", "Gadag", "Gulbarga", "Hassan", "Haveri",
  "Kodagu", "Kolar", "Koppal", "Mandya", "Mysore",
  "Raichur", "Ramanagara", "Shimoga", "Tumkur", "Udupi",
  "UttaraKannada", "Yadgir", "Alappuzha", "Ernakulam", "Idukki",
  "Kannur", "Kasaragod", "Kollam", "Kottayam", "Kozhikode",
  "Malappuram", "Palakkad", "Pathanamthitta", "Thiruvananthapuram", "Thrissur",
  "Wayanad", "Lakshadweep", "AgarMalwa", "Alirajpur", "Anuppur",
  "Ashoknagar", "Balaghat", "Barwani", "Betul", "Bhind",
  "Bhopal", "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh",
  "Datia", "Dewas", "Dhar", "Dindori", "EastNimar",
  "Guna", "Gwalior", "Harda", "Hoshangabad", "Indore",
  "Jabalpur", "Jhabua", "Katni", "Mandla", "Mandsaur",
  "Morena", "Narsimhapur", "Neemuch", "Panna", "Raisen",
  "Rajgarh", "Ratlam", "Rewa", "Sagar", "Satna",
  "Sehore", "Seoni", "Shahdol", "Shajapur", "Sheopur",
  "Shivpuri", "Sidhi", "Singrauli", "Tikamgarh", "Ujjain",
  "Umaria", "Vidisha", "WestNimar", "Ahmadnagar", "Akola",
  "Amravati", "Bhandara", "Bid", "Buldana", "Chandrapur",
  "Dhule", "Garhchiroli", "Gondiya", "Hingoli", "Jalgaon",
  "Jalna", "Kolhapur", "Latur", "MumbaiCity", "MumbaiSuburban",
  "Nagpur", "Nanded", "Nandurbar", "Nashik", "Osmanabad",
  "Palghar", "Parbhani", "Pune", "Ratnagiri", "Sangli",
  "Satara", "Sindhudurg", "Solapur", "Thane", "Wardha",
  "Washim", "Yavatmal", "Bishnupur", "Chandel", "Churachandpur",
  "ImphalEast", "ImphalWest", "Senapati", "Tamenglong", "Thoubal",
  "Ukhrul", "EastGaroHills", "EastKhasiHills", "JaintiaHills", "NorthGaroHills",
  "RiBhoi", "SouthGaroHills", "SouthWestGaroHills", "SouthWestKhasiHills", "WestGaroHills",
  "WestKhasiHills", "Aizawl", "Champhai", "Kolasib", "Lawangtlai",
  "Lunglei", "Mamit", "Saiha", "Serchhip", "Dimapur",
  "Kiphire", "Kohima", "Longleng", "Mokokchung", "Mon",
  "Peren", "Phek", "Tuensang", "Wokha", "Zunheboto",
  "West", "Anugul", "Balangir", "Baleshwar", "Bargarh",
  "Bauda", "Bhadrak", "Cuttack", "Debagarh", "Dhenkanal",
  "Gajapati", "Ganjam", "Jagatsinghapur", "Jajapur", "Jharsuguda",
  "Kalahandi", "Kandhamal", "Kendrapara", "Kendujhar", "Khordha",
  "Koraput", "Malkangiri", "Mayurbhanj", "Nabarangapur", "Nayagarh",
  "Nuapada", "Puri", "Rayagada", "Sambalpur", "Subarnapur",
  "Sundargarh", "Karaikal", "Mahe", "Puducherry", "Yanam",
  "Amritsar", "Barnala", "Bathinda", "Faridkot", "FatehgarhSahib",
  "Fazilka", "Firozpur", "Gurdaspur", "Hoshiarpur", "Jalandhar",
  "Kapurthala", "Ludhiana", "Mansa", "Moga", "Muktsar",
  "Pathankot", "Patiala", "Rupnagar", "SahibzadaAjitSinghNagar", "Sangrur",
  "ShahidBhagatSinghNagar", "TarnTaran", "Ajmer", "Alwar", "Banswara",
  "Baran", "Barmer", "Bharatpur", "Bhilwara", "Bikaner",
  "Bundi", "Chittaurgarh", "Churu", "Dausa", "Dhaulpur",
  "Dungarpur", "Ganganagar", "Hanumangarh", "Jaipur", "Jaisalmer",
  "Jalor", "Jhalawar", "Jhunjhunun", "Jodhpur", "Karauli",
  "Kota", "Nagaur", "Pali", "Pratapgarh", "Rajsamand",
  "SawaiMadhopur", "Sikar", "Sirohi", "Tonk", "Udaipur",
  "EastSikkim", "NorthSikkim", "SouthSikkim", "WestSikkim", "Ariyalur",
  "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri", "Dindigul",
  "Erode", "Kancheepuram", "Kanniyakumari", "Karur", "Krishnagiri",
  "Madurai", "Nagappattinam", "Namakkal", "Perambalur", "Pudukkottai",
  "Ramanathapuram", "Salem", "Sivaganga", "Thanjavur", "TheNilgiris",
  "Theni", "Thiruvallur", "Thiruvarur", "Thoothukkudi", "Tiruchirappalli",
  "Tirunelveli", "Tiruppur", "Tiruvannamalai", "Vellore", "Viluppuram",
  "Virudunagar", "Adilabad", "Hyderabad", "Karimnagar", "Khammam",
  "Mahbubnagar", "Medak", "Nalgonda", "Nizamabad", "RangaReddy",
  "Warangal", "Dhalai", "Gomati", "Khowai", "NorthTripura",
  "Sipahijala", "SouthTripura", "Unokoti", "WestTripura", "Agra",
  "Aligarh", "Allahabad", "AmbedkarNagar", "Amethi", "Amroha",
  "Auraiya", "Azamgarh", "Baghpat", "Bahraich", "Ballia",
  "Banda", "Barabanki", "Bareilly", "Basti", "Bijnor",
  "Budaun", "Bulandshahr", "Chandauli", "Chitrakoot", "Deoria",
  "Etah", "Etawah", "Faizabad", "Farrukhabad", "Fatehpur",
  "Firozabad", "GautamBuddhaNagar", "Ghaziabad", "Ghazipur", "Gonda",
  "Gorakhpur", "Hapur", "Hardoi", "Hathras", "Jalaun",
  "Jaunpur", "Jhansi", "Kannauj", "KanpurDehat", "KanpurNagar",
  "Kasganj", "Kaushambi", "Kushinagar", "LakhimpurKheri", "Lalitpur",
  "Lucknow", "Maharajganj", "Mahoba", "Mainpuri", "Mathura",
  "Mau", "Meerut", "Mirzapur", "Moradabad", "Muzaffarnagar",
  "Pilibhit", "RaeBareli", "Rampur", "Saharanpur", "Sambhal",
  "SantKabirNagar", "SantRaviDasNagar", "Shahjahanpur", "Shamli", "Shravasti",
  "SiddharthNagar", "Sitapur", "Sonbhadra", "Sultanpur", "Unnao",
  "Varanasi", "Almora", "Bageshwar", "Chamoli", "Champawat",
  "Dehradun", "Garhwal", "Hardwar", "Nainital", "Pithoragarh",
  "Rudraprayag", "TehriGarhwal", "UdhamSinghNagar", "Uttarkashi", "Alipurduar",
  "Bankura", "Barddhaman", "Birbhum", "DakshinDinajpur", "Darjiling",
  "Haora", "Hugli", "Jalpaiguri", "KochBihar", "Kolkata",
  "Maldah", "Murshidabad", "Nadia", "North24Parganas", "PashchimMedinipur",
  "PurbaMedinipur", "Puruliya", "South24Parganas", "UttarDinajpur"
)
```



```{r}
# Compare the vectors
same_length <- length(nfhs_district_names) == length(gadm_district_names)
same_length

```


```{r}
common_districts <- intersect(nfhs_district_names, gadm_district_names)

# Print the common districts
print("Common Districts:")
print(common_districts)
```


```{r}
# Identify mismatched districts
nfhs_not_in_gadm <- setdiff(nfhs_district_names, gadm_district_names)
gadm_not_in_nfhs <- setdiff(gadm_district_names, nfhs_district_names)

# Print the results
cat("Number of districts in NFHS not in GADM: ", length(nfhs_not_in_gadm), "\n")
cat("Number of districts in GADM not in NFHS: ", length(gadm_not_in_nfhs), "\n")
```


```{r}

library(stringdist)

# Perform fuzzy matching with a threshold for string similarity
fuzzy_matches <- sapply(nfhs_not_in_gadm, function(x) {
  match <- amatch(x, gadm_not_in_nfhs, maxDist = 2) 
  if (!is.na(match)) {
    return(c(NFHS = x, GADM = gadm_not_in_nfhs[match]))
  } else {
    return(NULL)
  }
})

# Filter out the NULL matches
fuzzy_matches <- do.call(rbind, fuzzy_matches)

# Print the fuzzy matches
print("Potential fuzzy matches between NFHS and GADM:")
print(fuzzy_matches)


```

```{r}
# Create a dictionary for mapping GADM district names to NFHS district names
gadm_to_nfhs_map <- list(
  "Poonch" = "Punch",
  "Baramulla" = "Baramula",
  "Lahul&Spiti" = "Lahul & Spiti",
  "FatehgarhSahib" = "Fatehgarh Sahib",
  "TarnTaran" = "Tarn Taran",
  "TehriGarhwal" = "Tehri Garhwal",
  "UdhamSinghNagar" = "Udham Singh Nagar",
  "SawaiMadhopur" = "Sawai Madhopur",
  "GautamBuddhaNagar" = "Gautam Buddha Nagar",
  "KanpurDehat" = "Kanpur Dehat",
  "KanpurNagar" = "Kanpur Nagar",
  "Barabanki" = "Bara Banki",
  "AmbedkarNagar" = "Ambedkar Nagar",
  "Shravasti" = "Shrawasti",
  "SiddharthNagar" = "Siddharthnagar",
  "SantKabirNagar" = "Sant Kabir Nagar",
  "Maharajganj" = "Mahrajganj",
  "PashchimChamparan" = "Pashchim Champaran",
  "PurbaChamparan" = "Purba Champaran",
  "WestKameng" = "West Kameng",
  "EastKameng" = "East Kameng",
  "PapumPare" = "Papum Pare",
  "UpperSubansiri" = "Upper Subansiri",
  "UpperSiang" = "Upper Siang",
  "LowerSubansiri" = "Lower Subansiri",
  "DibangValley" = "Dibang Valley",
  "LowerDibangValley" = "Lower Dibang Valley",
  "ImphalWest" = "Imphal West",
  "ImphalEast" = "Imphal East",
  "Lawangtlai" = "Lawngtlai",
  "SouthGaroHills" = "South Garo Hills",
  "RiBhoi" = "Ribhoi",
  "EastKhasiHills" = "East Khasi Hills",
  "DimaHasao" = "Dima Hasao",
  "KamrupMetropolitan" = "Kamrup Metropolitan",
  "KochBihar" = "Koch Bihar",
  "UttarDinajpur" = "Uttar Dinajpur",
  "DakshinDinajpur" = "Dakshin Dinajpur",
  "PashchimMedinipur" = "Paschim Medinipur",
  "PurbaMedinipur" = "Purba Medinipur",
  "PurbiSinghbhum" = "Purbi Singhbhum",
  "PashchimiSinghbhum" = "Pashchimi Singhbhum",
  "Saraikela-kharsawan" = "Saraikela-Kharsawan",
  "Bauda" = "Baudh",
  "Janjgir-Champa" = "Janjgir - Champa",
  "UttarBastarKanker" = "Uttar Bastar Kanker",
  "BanasKantha" = "Banas Kantha",
  "Dahod" = "Dohad",
  "TheDangs" = "The Dangs",
  "Garhchiroli" = "Gadchiroli",
  "MumbaiSuburban" = "Mumbai Suburban",
  "EastGodavari" = "East Godavari",
  "WestGodavari" = "West Godavari",
  "UttaraKannada" = "Uttara Kannada",
  "DakshinaKannada" = "Dakshina Kannada",
  "Chamrajnagar" = "Chamarajanagar",
  "Chikballapura" = "Chikkaballapura",
  "BangaloreRural" = "Bangalore Rural",
  "NorthGoa" = "North Goa",
  "SouthGoa" = "South Goa",
  "TheNilgiris" = "The Nilgiris",
  "Nagappattinam" = "Nagapattinam",
  "Virudunagar" = "Virudhunagar",
  "SouthAndaman" = "South Andaman",
  "EastSiang" = "East Siang",
  "KurungKumey" = "Kurung Kumey",
  "WestSiang" = "West Siang",
  "KarbiAnglong" = "Karbi Anglong",
  "BalodaBazar" = "Baloda Bazar",
  "Gariaband" = "Gariyaband",
  "Kondagaon" = "Kodagaon",
  "Aravalli" = "Aravali",
  "ChhotaUdaipur" = "Chhota Udaipur",
  "DevbhumiDwarka" = "Devbhumi Dwarka",
  "GirSomnath" = "Gir Somnath",
  "PanchMahals" = "Panch Mahals",
  "SabarKantha" = "Sabar Kantha",
  "AgarMalwa" = "Agar Malwa",
  "EastGaroHills" = "East Garo Hills",
  "NorthGaroHills" = "North Garo Hills",
  "WestGaroHills" = "West Garo Hills",
  "WestKhasiHills" = "West Khasi Hills",
  "Mahbubnagar" = "Mahabubnagar",
  "RangaReddy" = "Ranga Reddy",
  "NorthTripura" = "North Tripura",
  "Sipahijala" = "Sepahijala",
  "SouthTripura" = "South Tripura",
  "Unokoti" = "Unakoti",
  "WestTripura" = "West Tripura",
  "RaeBareli" = "Rae Bareli",
  "ShahidBhagatSinghNagar" = "Shahid Bhagat Singh Nagar",
  "SahibzadaAjitSinghNagar" = "Sahibzada Ajit Singh Nagar",
  "LakhimpurKheri" = "Kheri",
  "DadraandNagarHaveli" = "Dadra & Nagar Haveli",
  "MumbaiCity" = "Mumbai",
  "NorthandMiddleAndaman" = "North & Middle Andaman",
  "NicobarIslands" = "Nicobars",
  "Nellore" = "Sri Potti Sriramulu Nellore",
  "North24Parganas" = "North Twenty Four Parganas",
  "South24Parganas" = "South Twenty Four Parganas",
  "Barddhaman" = "Purba Barddhaman",
  "EastNimar" = "Khandwa (East Nimar)",
  "Kaimur" = "Kaimur (Bhabua)",
  "WestNimar" = "Khargone (West Nimar)",
  "JaintiaHills" = "East Jantia Hills",
  "SouthWestGaroHills" = "South West Garo Hills",
  "SantRaviDasNagar" = "Sant Ravidas Nagar (Bhadohi)",
  "Hathras" = "Mahamaya Nagar",
  "Kasganj" = "Kanshiram Nagar",
  "Warangal" = "Warangal Rural",
  "Amroha" = "Jyotiba Phule Nagar",
  "NorthSikkim" = "North District",
  "SouthSikkim" = "South District",
  "EastSikkim" = "East District",
  "WestSikkim" = "West District",
  "SouthWestKhasiHills" = "South West Khasi Hills"
)

# Convert to a named vector for easier replacement
gadm_to_nfhs_map <- unlist(gadm_to_nfhs_map)
```


```{r}
# Update the Names_2 column
india_districts <- india_districts %>%
  mutate(NAME_2 = ifelse(NAME_2 %in% names(gadm_to_nfhs_map), gadm_to_nfhs_map[NAME_2], NAME_2))

# Print the updated names for verification
print("Updated NAME_2 column:")
print(india_districts$NAME_2)

```



## Created an excel file with the labels of NFHS districts


```{r}
library(readxl)
districts<- read_excel("sdist_disticts.xlsx")
districts
```



## SGA Mapping of GROW


```{r}
# Read the entire sheet
data <- read_excel("GROW_district_sga_prevalence.xlsx")
print (data)
```


```{r}
# Count the number of unique sdist variables
unique_sdist_count <- data %>% 
  distinct(sdist) %>%
  count()

# Print the count
print(unique_sdist_count)
```






```{r}
# Perform the merge using left_join (can use inner_join, right_join, full_join as needed)
districts_GROW<- left_join(districts, data, by = "sdist")
merged_data <- left_join(india_districts, districts_GROW, by = "NAME_2")

# View the merged data
print(merged_data)
```


```{r}
# Filter out rows with NA in the 'prevalence of SGA' column
cleaned_data_merged <- merged_data %>%
  filter(!is.na(`prevalence of SGA`))

# Replace NA values in the 'prevalence of SGA' column with "NA"
cleaned_data_merged$`prevalence of SGA`[is.na(cleaned_data_merged$`prevalence of SGA`)] <- "NA"

# Convert to factor to handle colors in ggplot
cleaned_data_merged$`prevalence of SGA` <- factor(cleaned_data_merged$`prevalence of SGA`)

# Print the cleaned data
print(cleaned_data_merged)
```



```{r}
#Using typeof()
typeof(cleaned_data_merged$geometry)
typeof(cleaned_data_merged$prevalence_of_SGA)
```


```{r}
library(dplyr)

# Convert 'prevalence of SGA' to numeric, replacing "NA" strings with actual NA values
cleaned_data_merged <- merged_data %>%
  mutate(`prevalence of SGA` = as.numeric(as.character(`prevalence of SGA`)))

# Remove rows where 'prevalence of SGA' is NA
cleaned_data_merged <- cleaned_data_merged %>%
  filter(!is.na(`prevalence of SGA`))

# Ensure it's an sf object
cleaned_data_merged <- st_as_sf(cleaned_data_merged)
```




```{r}
library(viridis)

ggplot() +
  geom_sf(data = cleaned_data_merged, aes(fill = `prevalence of SGA`), color = NA, size = 0.1) +
  scale_fill_viridis(option = "plasma", direction = -1, name = "SGA Prevalence (%)", 
                     na.value = "grey50",
                     guide = guide_colorbar(barwidth = 15, barheight = 0.5),
                     limits = c(0, 65)) +
  labs(title = "Prevalence of Small for Gestational Age (SGA) by Districts in India",
       subtitle = "Based on GROW Standard") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "bottom",
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )


```

```{r}
# Assuming 95% confidence level, Z-score is 1.96
z_score <- 1.96

# Calculate the confidence intervals
cleaned_data_merged <- cleaned_data_merged %>%
  mutate(
    Lower_CI = `prevalence of SGA` - z_score * `standard error of SGA`,
    Upper_CI = `prevalence of SGA` + z_score * `standard error of SGA`
  )

# Ensure the CIs are within valid bounds [0, 100]
cleaned_data_merged <- cleaned_data_merged %>%
  mutate(
    Lower_CI = pmax(Lower_CI, 0),
    Upper_CI = pmin(Upper_CI, 100)
  )

```



```{r}
# Calculate CI width
cleaned_data_merged <- cleaned_data_merged %>%
  mutate(CI_width = Upper_CI - Lower_CI)

# Determine limits
max_width <- max(cleaned_data_merged$CI_width)
min_width <- min(cleaned_data_merged$CI_width)
limits <- c(min_width, max_width)
limits
```


```{r}
ggplot() +
  geom_sf(data = cleaned_data_merged, aes(fill = CI_width), color = NA, size = 0.1) +
  scale_fill_viridis(option = "plasma", direction = -1, 
                     name = "CI Width (%)", 
                     na.value = "grey50",
                     guide = guide_colorbar(barwidth = 15, barheight = 0.5),
                     limits = c(0, 35)) +  # Adjusted based on maximum CI_width value
  labs(title = "Width of 95% Confidence Intervals for SGA Prevalence by Districts in India",
       subtitle = "Based on GROW Standard") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "bottom",
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )


```




```{r}
library(leaflet)
library(htmlwidgets)
library(htmltools)

create_interactive_state_map <- function(state_name, cleaned_data_merged) {
  # Filter data for the specific state
  state_data <- cleaned_data_merged %>%
    filter(NAME_1 == state_name)
  
  # Convert to an interactive map
  map <- leaflet(state_data) %>%
    addTiles() %>%
    addPolygons(
      fillColor = ~colorNumeric("plasma", `prevalence of SGA`, reverse = TRUE)(`prevalence of SGA`),
      color = "white", 
      weight = 1,
      opacity = 1,
      fillOpacity = 0.7,
      popup = ~paste0(
        "District: ", NAME_2, "<br>",
        "SGA Prevalence: ", round(`prevalence of SGA`, 2), "%<br>",
        "CI: ", round(Lower_CI, 2), "-", round(Upper_CI, 2), "%"
      )
    ) %>%
    addLegend(
      "bottomright", 
      pal = colorNumeric("plasma", NULL, reverse = TRUE),
      values = ~`prevalence of SGA`,
      title = "SGA Prevalence (%)",
      opacity = 1
    )
  
  # Add title and subtitle using HTML
  title_html <- tags$div(
    tags$h3(paste("Prevalence of Small for Gestational Age (SGA) in", state_name)),
    tags$h5("Based on GROW Standard")
  )
  
  map <- map %>%
    addControl(title_html, position = "topright", className = "map-title")
  
  # Custom CSS for the title
  css <- "
    .map-title {
      font-weight: bold;
      text-align: center;
      background: white;
      padding: 5px;
      border-radius: 5px;
      box-shadow: 0px 0px 5px rgba(0,0,0,0.2);
    }
    .leaflet-control {
      background: none;
      border: none;
    }
  "
  
  map <- map %>%
    htmlwidgets::onRender("
      function(el, x) {
        var css = `${css}`;
        var head = document.head || document.getElementsByTagName('head')[0];
        var style = document.createElement('style');
        style.type = 'text/css';
        if (style.styleSheet) {
          style.styleSheet.cssText = css;
        } else {
          style.appendChild(document.createTextNode(css));
        }
        head.appendChild(style);
      }
    ")
  
  map
}

# Get unique state names from the cleaned_data_merged dataset
state_names <- unique(cleaned_data_merged$NAME_1)

# Create interactive maps for all states
for (state in state_names) {
  map <- create_interactive_state_map(state, cleaned_data_merged)
  saveWidget(map, paste0(state, "_SGA_map.html"), selfcontained = TRUE)
}

```




```{r}
create_state_map <- function(state_name, cleaned_data_merged) {
  # Filter data for the specific state
  state_data <- cleaned_data_merged %>%
    filter(NAME_1 == state_name)
  
  # Create the map
  ggplot() +
    geom_sf(data = state_data, aes(fill = `prevalence of SGA`), color = "white", size = 0.1) +
    scale_fill_viridis(option = "plasma", name = "SGA Prevalence (%)", 
                       na.value = "grey50",
                       guide = guide_colorbar(barwidth = 15, barheight = 0.5)) +
    labs(title = paste("Prevalence of Small for Gestational Age (SGA) in", state_name),
         subtitle = "Based on GROW Standard") +
    theme_minimal() +
    theme(
      plot.title = element_text(hjust = 0.5, face = "bold"),
      legend.position = "bottom",
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      panel.grid = element_blank()
    )
}

# First, get unique state names from the cleaned_data_merged dataset
state_names <- unique(cleaned_data_merged$NAME_1)

# Now, create maps for all states
for (state in state_names) {
  map <- create_state_map(state, cleaned_data_merged)
  print(map)
  ggsave(paste0(state, "_SGA_map.png"), map, width = 10, height = 8, dpi = 300)
}
```



```{r}
# Ensure the CRS is in a format Leaflet can use (WGS84)
cleaned_data_merged <- st_transform(cleaned_data_merged, 4326)

# Create a color palette using "inferno"
pal <- colorNumeric(
  palette = "inferno",  # Using inferno palette
  domain = cleaned_data_merged$`prevalence of SGA`,
  reverse = TRUE  # Reverse the color scale
)

# Create the formatted labels
cleaned_data_merged$label <- paste0(
  "State: <strong>", cleaned_data_merged$NAME_1, "</strong><br>",
  "District: <strong>", cleaned_data_merged$NAME_2, "</strong><br>",
  "Prevalence: <strong>", round(cleaned_data_merged$`prevalence of SGA`, 2), "%</strong><br>",
  "95% CI: <strong>", round(cleaned_data_merged$Lower_CI, 2), "% - ", round(cleaned_data_merged$Upper_CI, 2), "%</strong>"
)

# Create the map
map <- leaflet(cleaned_data_merged) %>%
  addTiles(urlTemplate = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png") %>%  # Replace with a stable tile server URL
  addPolygons(
    fillColor = ~pal(`prevalence of SGA`),
    weight = 1,  # Reduced weight for the outlines
    opacity = 1,
    color = "#B0B0B0",  # Light gray color for the outlines
    dashArray = "3",
    fillOpacity = 0.7,
    highlightOptions = highlightOptions(
      weight = 3,  # Highlight weight is also reduced
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = ~lapply(label, htmltools::HTML),  # Use the new formatted labels
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    pal = pal,
    values = ~`prevalence of SGA`,
    opacity = 0.7,
    title = "SGA Prevalence using GROW standard(%)",
    position = "bottomright"
  )

# Save the map to an HTML file
saveWidget(map, file = "GROW_SGA_prevalence_map.html")

# Display the map
map
```



## Fay-Herriot model for SGA using GROW


```{r}
GROW_data <- cleaned_data_merged %>%
  rename(
    prevalence = `prevalence of SGA`,
    standarderror = `standard error of SGA`
  )
```



```{r}
# Compute sampling variances from standard errors
GROW_data <- GROW_data  %>%
  mutate(sampling_variance = standarderror^2)

print (GROW_data)
```



```{r}
GROW_data <- as.data.frame(GROW_data)

library(sae)

# Fit the Fay-Herriot model
fh_model <- try(mseFH(
  formula = prevalence ~ 1, 
  vardir = sampling_variance, 
  data = GROW_data
))

fh_model
```



```{r}
# Extract the results
GROW_data$FH_estimate <- fh_model$est$eblup

# Extract MSE values and add them to GROW_data
GROW_data$MSE <- fh_model$mse

GROW_data
```




```{r}
library(gridExtra)

# Scatter plot comparing original prevalence with FH estimates
ggplot(GROW_data, aes(x = prevalence, y = FH_estimate)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
  labs(x = "Original Prevalence", y = "Fay-Herriot Estimate",
       title = "Comparison of Prevalence of SGA using GROW standard and Fay-Herriot Estimates")+
  theme(plot.title = element_text(size = 13, margin = margin(b = 10)))


# Adjusting the theme for better title display
p1 <- ggplot(GROW_data, aes(x = prevalence)) +
  geom_histogram(bins = 30, fill = "blue", alpha = 0.5) +
  labs(title = "Prevalence of SGA using GROW standard") +
  theme(plot.title = element_text(size = 9, margin = margin(b = 10)))

p2 <- ggplot(GROW_data, aes(x = FH_estimate)) +
  geom_histogram(bins = 30, fill = "red", alpha = 0.5) +
  labs(title = "Fay-Herriot Estimates of SGA using GROW standard") +
  theme(plot.title = element_text(size = 9, margin = margin(b = 10)))

# Arranging the plots in a grid
grid.arrange(p1, p2, ncol = 2)

```
```{r}
# Model Diagnostics

# Calculate residuals
GROW_data$residuals <- GROW_data$prevalence - GROW_data$FH_estimate

# Residual plot
ggplot(GROW_data, aes(x = FH_estimate, y = residuals)) +
  geom_point() +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  labs(x = "Fitted Values", y = "Residuals",
       title = "Residual Plot for Fay-Herriot Model (SGA using GROW standard)")

# QQ plot
qqnorm(GROW_data$residuals)
qqline(GROW_data$residuals, col = "red")

```

```{r}
# Calculate 95% CI for FH estimates
GROW_data$FH_lower_CI <- GROW_data$FH_estimate - 1.96 * sqrt(GROW_data$MSE)
GROW_data$FH_upper_CI <- GROW_data$FH_estimate + 1.96 * sqrt(GROW_data$MSE)

GROW_data
```


```{r}
# Comparison Analysis

# Calculate CI width for original and FH estimates
GROW_data$FH_CI_width <- GROW_data$FH_upper_CI - GROW_data$FH_lower_CI

# Calculate mean CI width for comparison
mean_original_CI_width <- mean(GROW_data$CI_width)
mean_fh_CI_width <- mean(GROW_data$FH_CI_width)

# Print or plot the comparison
cat("Mean width of original CIs:", mean_original_CI_width, "\n")
cat("Mean width of Fay-Herriot CIs:", mean_fh_CI_width, "\n")

```

```{r}
# Determine limits
max_width <- max(GROW_data$FH_CI_width)
min_width <- min(GROW_data$FH_CI_width)
limits <- c(min_width, max_width)
limits
```

```{r}
# Create the plot with adjusted title
ggplot(GROW_data, aes(x = CI_width, y = FH_CI_width)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
  labs(x = "Original CI Width", y = "Fay-Herriot CI Width",
       title = "Comparison of SGA Confidence Interval Widths: GROW Standard vs. Fay-Herriot Model") +
  theme(plot.title = element_text(size = 12, margin = margin(b = 10)))



```

```{r}
# Convert 'prevalence of SGA' to numeric, replacing "NA" strings with actual NA values
GROW_data <- GROW_data %>%
  mutate( FH_estimate = as.numeric(as.character(FH_estimate)))

# Remove rows where 'prevalence of SGA' is NA
GROW_data <- GROW_data %>%
  filter(!is.na(FH_estimate))

# Ensure it's an sf object
GROW_data <- st_as_sf(GROW_data)
```



```{r}
ggplot() +
  geom_sf(data = GROW_data, aes(fill = FH_estimate), color = NA, size = 0.1) +
  scale_fill_viridis(option = "plasma", direction = -1, name = "SGA Prevalence through smoothing (%)", 
                     na.value = "grey50",
                     guide = guide_colorbar(barwidth = 15, barheight = 0.5),
                     limits = c(0, 65)) +
  labs(title = "Prevalence of SGA by Districts in India (After Fay-Herriot model)",
       subtitle = "Based on GROW Standard") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "bottom",
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )


```


```{r}
ggplot() +
  geom_sf(data = GROW_data, aes(fill = FH_CI_width), color = NA, size = 0.1) +
  scale_fill_viridis(option = "plasma", direction = -1, 
                     name = "CI Width (%)", 
                     na.value = "grey50",
                     guide = guide_colorbar(barwidth = 15, barheight = 0.5),
                     limits = c(0, 35)) +  # Adjusted based on maximum CI_width value
  labs(title = "Width of 95% Confidence Intervals for SGA Prevalence by Districts in India",
       subtitle = "Based on GROW Standard (After Fay-Herriot model)") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "bottom",
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )


```



## SGA Mapping by using INTERGROWTH 


```{r}

data <- read_excel("Intergrowth_district_sga_prevalence.xlsx")
districts<- read_excel("sdist_disticts.xlsx")

# Perform the merge using left_join (can use inner_join, right_join, full_join as needed)
districts_SGA_inter<- left_join(districts, data, by = "sdist")
merged_data_districts_SGA <- left_join(india_districts, districts_SGA_inter, by = "NAME_2")

# View the merged data
print(merged_data_districts_SGA)
```


```{r}
cleaned_data_merged<- merged_data_districts_SGA %>%filter(!is.na(prevalence_of_SGA))

cleaned_data_merged$prevalence_of_SGA[is.na(cleaned_data_merged$prevalence_of_SGA)] <-"NA"

# Convert to factor to handle colors in ggplot
cleaned_data_merged$prevalence_of_SGA <- factor(cleaned_data_merged$prevalence_of_SGA)
print(cleaned_data_merged)
```


```{r}
# Clean and prepare the data
cleaned_data_merged <- merged_data_districts_SGA %>%
  mutate(prevalence_of_SGA = as.numeric(as.character(prevalence_of_SGA))) %>%
  filter(!is.na(prevalence_of_SGA))

# Ensure it's an sf object
cleaned_data_merged <- st_as_sf(cleaned_data_merged)

print(cleaned_data_merged)
```


```{r}
ggplot() +
  geom_sf(data = cleaned_data_merged, aes(fill = prevalence_of_SGA), color = NA, size = 0.1) +
  scale_fill_viridis(option = "plasma", direction = -1, name = "SGA Prevalence (%)", 
                     na.value = "grey50",
                     guide = guide_colorbar(barwidth = 15, barheight = 0.5), 
                     limits = c(0, 65))+
  labs(title = "Prevalence of Small for Gestational Age (SGA) by District in India",
       subtitle = "Based on INTERGROWTH-21st Standard") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5),
    legend.position = "bottom",
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )

```


```{r}
create_state_map <- function(state_name, cleaned_data_merged) {
  # Filter data for the specific state
  state_data <- cleaned_data_merged %>%
    filter(NAME_1 == state_name)
  
  # Create the map
  ggplot() +
    geom_sf(data = state_data, aes(fill = prevalence_of_SGA), color = "white", size = 0.1) +
    scale_fill_viridis(option = "plasma", name = "SGA Prevalence (%)", 
                       na.value = "grey50",
                       guide = guide_colorbar(barwidth = 15, barheight = 0.5)) +
    labs(title = paste("Prevalence of Small for Gestational Age (SGA) in", state_name),
         subtitle = "Based on INTERGROWTH-21st Standard") +
    theme_minimal() +
    theme(
      plot.title = element_text(hjust = 0.5, face = "bold"),
      legend.position = "bottom",
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      panel.grid = element_blank()
    )
}

# First, get unique state names from the cleaned_data_merged dataset
state_names <- unique(cleaned_data_merged$NAME_1)

# Now, create maps for all states
for (state in state_names) {
  map <- create_state_map(state, cleaned_data_merged)
  print(map)
  ggsave(paste0(state, "_SGA_map.png"), map, width = 10, height = 8, dpi = 300)
}

```


```{r}
# Assuming 95% confidence level, Z-score is 1.96
z_score <- 1.96

# Calculate the confidence intervals
cleaned_data_merged <- cleaned_data_merged %>%
  mutate(
    Lower_CI_IN = prevalence_of_SGA - z_score * `standard error of SGA`,
    Upper_CI_IN = prevalence_of_SGA + z_score * `standard error of SGA`
  )

# Ensure the CIs are within valid bounds [0, 100]
cleaned_data_merged <- cleaned_data_merged %>%
  mutate(
    Lower_CI_IN = pmax(Lower_CI_IN, 0),
    Upper_CI_IN = pmin(Upper_CI_IN, 100)
  )

```


```{r}
library(ggplot2)
library(sf)
library(viridis)
library(dplyr)

# Calculate CI width
cleaned_data_merged <- cleaned_data_merged %>%
  mutate(CI_width_IN = Upper_CI_IN - Lower_CI_IN)

# Determine limits
max_width_IN <- max(cleaned_data_merged$CI_width_IN)
min_width_IN <- min(cleaned_data_merged$CI_width_IN)
limits_IN <- c(min_width_IN, max_width_IN)
limits_IN
```


```{r}
ggplot() +
  geom_sf(data = cleaned_data_merged, aes(fill = CI_width_IN), color = NA, size = 0.1) +
  scale_fill_viridis(option = "plasma", direction = -1, 
                     name = "CI Width (%)", 
                     na.value = "grey50",
                     guide = guide_colorbar(barwidth = 15, barheight = 0.5),
                     limits = c(0, 35)) +  # Adjusted based on maximum CI_width_IN value
  labs(title = "Width of 95% Confidence Intervals for SGA Prevalence by Districts in India",
       subtitle = "Based on INTERGROWTH-21st Standard") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "bottom",
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )


```







```{r}
create_interactive_state_map <- function(state_name, cleaned_data_merged) {
  # Filter data for the specific state
  state_data <- cleaned_data_merged %>%
    filter(NAME_1 == state_name)
  
  # Convert to an interactive map
  map <- leaflet(state_data) %>%
    addTiles() %>%
    addPolygons(
      fillColor = ~colorNumeric("plasma", prevalence_of_SGA, reverse = TRUE)(prevalence_of_SGA),
      color = "white", 
      weight = 1,
      opacity = 1,
      fillOpacity = 0.7,
      popup = ~paste0(
        "District: ", NAME_2, "<br>",
        "SGA Prevalence: ", round(prevalence_of_SGA, 2), "%<br>",
        "CI: ", round( Lower_CI_IN, 2), "-", round(Upper_CI_IN, 2), "%"
      )
    ) %>%
    addLegend(
      "bottomright", 
      pal = colorNumeric("plasma", NULL, reverse = TRUE),
      values = ~ prevalence_of_SGA,
      title = "SGA Prevalence (%)",
      opacity = 1
    )
  
  # Add title and subtitle using HTML
  title_html <- tags$div(
    tags$h3(paste("Prevalence of Small for Gestational Age (SGA) in", state_name)),
    tags$h5("Based on INTERGROWTH-21st Standard")
  )
  
  map <- map %>%
    addControl(title_html, position = "topright", className = "map-title")
  
  # Custom CSS for the title
  css <- "
    .map-title {
      font-weight: bold;
      text-align: center;
      background: white;
      padding: 5px;
      border-radius: 5px;
      box-shadow: 0px 0px 5px rgba(0,0,0,0.2);
    }
    .leaflet-control {
      background: none;
      border: none;
    }
  "
  
  map <- map %>%
    htmlwidgets::onRender("
      function(el, x) {
        var css = `${css}`;
        var head = document.head || document.getElementsByTagName('head')[0];
        var style = document.createElement('style');
        style.type = 'text/css';
        if (style.styleSheet) {
          style.styleSheet.cssText = css;
        } else {
          style.appendChild(document.createTextNode(css));
        }
        head.appendChild(style);
      }
    ")
  
  map
}

# Get unique state names from the cleaned_data_merged dataset
state_names <- unique(cleaned_data_merged$NAME_1)

# Create interactive maps for all states
for (state in state_names) {
  map <- create_interactive_state_map(state, cleaned_data_merged)
  saveWidget(map, paste0(state, "INTERGROWTH_SGA_map.html"), selfcontained = TRUE)
}



```











```{r}
# Ensure the CRS is in a format leaflet can use
cleaned_data_merged <- st_transform(cleaned_data_merged, 4326)

# Create a color palette using "inferno"
pal <- colorNumeric(
  palette = "inferno",  # Using inferno palette
  domain = cleaned_data_merged$prevalence_of_SGA,
  reverse = TRUE  # Reverse the color scale
)

# Create the formatted labels
cleaned_data_merged$label <- paste0(
  "State: <strong>", cleaned_data_merged$NAME_1, "</strong><br>",
  "District: <strong>", cleaned_data_merged$NAME_2, "</strong><br>",
  "Prevalence: <strong>", round(cleaned_data_merged$prevalence_of_SGA, 2), "%</strong><br>",
  "95% CI: <strong>", round(cleaned_data_merged$Lower_CI_IN, 2), "% - ", round(cleaned_data_merged$Upper_CI_IN, 2), "%</strong>"
)

# Create the map
map <- leaflet(cleaned_data_merged) %>%
  addTiles(urlTemplate = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png") %>%  # Replace with a stable tile server URL
  addPolygons(
    fillColor = ~pal(prevalence_of_SGA),
    weight = 1,  # Reduced weight for the outlines
    opacity = 1,
    color = "#B0B0B0",  # Light gray color for the outlines
    dashArray = "3",
    fillOpacity = 0.7,
    highlightOptions = highlightOptions(
      weight = 3,  # Highlight weight is also reduced
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = ~lapply(label, htmltools::HTML),  # Use the new formatted labels
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    pal = pal,
    values = ~ prevalence_of_SGA,
    opacity = 0.7,
    title = "SGA Prevalence using INTERGROWTH-21st standard (%)",
    position = "bottomright"
  )

# Save the map to an HTML file
saveWidget(map, file = "INTERGROWTH_SGA_prevalence_map.html")

# Display the map
map

```




## Fay-Herriot model for SGA using INTERGROWTH-21st


```{r}
INTR_data <- cleaned_data_merged %>%
  rename(
    INTRprevalence = prevalence_of_SGA,
    INTRstandarderror = `standard error of SGA`
  )
```



```{r}
# Compute sampling variances from standard errors
INTR_data <- INTR_data  %>%
  mutate(INTRsampling_variance = INTRstandarderror^2)

print (INTR_data)
```



```{r}
INTR_data <- as.data.frame(INTR_data)

library(sae)

# Fit the Fay-Herriot model
INTR_fh_model <- try(mseFH(
  formula = INTRprevalence ~ 1, 
  vardir = INTRsampling_variance, 
  data = INTR_data
))

INTR_fh_model
```



```{r}
# Extract the results
INTR_data$INTRFH_estimate <- INTR_fh_model$est$eblup

# Extract MSE values and add them to GROW_data
INTR_data$INTR_MSE <- INTR_fh_model$mse

INTR_data
```




```{r}
library(gridExtra)

# Scatter plot comparing original prevalence with FH estimates
ggplot(INTR_data, aes(x = INTRprevalence, y = INTRFH_estimate)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
  labs(x = "Original Prevalence", y = "Fay-Herriot Estimate",
       title = "Comparison of Prevalence of SGA using INTERGROWTH-21st Standard and Fay-Herriot Estimates") +
      theme (plot.title = element_text(size = 11, margin = margin(b=10)))

# Histograms

p1 <- ggplot(INTR_data, aes(x = INTRprevalence)) +
  geom_histogram(bins = 30, fill = "blue", alpha = 0.5) +
  labs(title = "Prevalence of SGA using INTERGROWTH-21st standard", x = "Prevalence") +
  theme(plot.title = element_text(size = 7, margin = margin(b = 10)))


p2 <- ggplot(INTR_data, aes(x = INTRFH_estimate)) +
  geom_histogram(bins = 30, fill = "red", alpha = 0.5) +
  labs(title = "Fay-Herriot Estimates of SGA using INTERGROWTH-21st standard", x = "FH_estimate") +
  theme(plot.title = element_text(size = 7, margin = margin(b = 10)))

# Arranging the plots in a grid
grid.arrange(p1, p2, ncol = 2)


```



```{r}
# Model Diagnostics

# Calculate residuals
INTR_data$residuals <- INTR_data$INTRprevalence - INTR_data$INTRFH_estimate

# Residual plot
ggplot(INTR_data, aes(x = INTRFH_estimate, y = residuals)) +
  geom_point() +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  labs(x = "Fitted Values", y = "Residuals",
       title = "Residual Plot for Fay-Herriot Model (SGA using INTERGROWTH-21st standard)")+
  theme (plot.title = element_text(size = 12, margin = margin(b=10)))


# QQ plot
qqnorm(INTR_data$residuals)
qqline(INTR_data$residuals, col = "red")

```

```{r}
# Calculate 95% CI for FH estimates
INTR_data$INTR_FH_lower_CI <- INTR_data$INTRFH_estimate - 1.96 * sqrt(INTR_data$INTR_MSE)
INTR_data$INTR_FH_upper_CI <- INTR_data$INTRFH_estimate + 1.96 * sqrt(INTR_data$INTR_MSE)

INTR_data
```


```{r}
# Comparison Analysis

# Calculate CI width for original and FH estimates
INTR_data$INTR_FH_CI_width <- INTR_data$INTR_FH_upper_CI - INTR_data$INTR_FH_lower_CI

# Calculate mean CI width for comparison
mean_original_CI_width_IN <- mean(INTR_data$CI_width_IN)
mean_fh_CI_width_IN <- mean(INTR_data$INTR_FH_CI_width)

# Print or plot the comparison
cat("Mean width of original CIs:", mean_original_CI_width_IN, "\n")
cat("Mean width of Fay-Herriot CIs:", mean_fh_CI_width_IN, "\n")

```

```{r}
# Determine limits
max_width <- max(INTR_data$INTR_FH_CI_width)
min_width <- min(INTR_data$INTR_FH_CI_width)
limits <- c(min_width, max_width)
limits
```

```{r}
# Compare CI widths
ggplot(INTR_data, aes(x = CI_width_IN, y = INTR_FH_CI_width)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
  labs(x = "Original CI Width", y = "Fay-Herriot CI Width",
       title = "Comparison of 95% CI Widths of SGA: INTERGROWTH-21st standard vs. Fay-Herriot Model")+
  theme (plot.title = element_text(size = 12, margin = margin(b=10)))
```




```{r}
# Convert 'prevalence of SGA' to numeric, replacing "NA" strings with actual NA values
INTR_data <- INTR_data %>%
  mutate( INTRFH_estimate = as.numeric(as.character(INTRFH_estimate)))

# Remove rows where 'prevalence of SGA' is NA
INTR_data <- INTR_data %>%
  filter(!is.na(INTRFH_estimate))

# Ensure it's an sf object
INTR_data <- st_as_sf(INTR_data)
```



```{r}
ggplot() +
  geom_sf(data = INTR_data, aes(fill = INTRFH_estimate), color = NA, size = 0.1) +
  scale_fill_viridis(option = "plasma", direction = -1, name = "SGA Prevalence through smoothing (%)", 
                     na.value = "grey50",
                     guide = guide_colorbar(barwidth = 15, barheight = 0.5),
                     limits = c(0, 65)) +
  labs(title = "Prevalence of SGA by Districts in India (After Fay-Herriot model)",
       subtitle = "Based on INTERGROWTH-21st Standard") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "bottom",
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )


```


```{r}
ggplot() +
  geom_sf(data = INTR_data, aes(fill = INTR_FH_CI_width), color = NA, size = 0.1) +
  scale_fill_viridis(option = "plasma", direction = -1, 
                     name = "CI Width (%)", 
                     na.value = "grey50",
                     guide = guide_colorbar(barwidth = 15, barheight = 0.5),
                     limits = c(0, 35)) +  
  labs(title = "Width of 95% Confidence Intervals for SGA Prevalence by Districts in India",
       subtitle = "Based on INTERGROWTH-21st Standard (After Fay-Herriot model)") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "bottom",
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )


```



## LBW plotting 


```{r}
# Read the entire sheet
data <- read_excel("LBW_district_sga_prevalence.xlsx")
districts<- read_excel("sdist_disticts.xlsx")
```


```{r}
# Perform the merge using left_join (can use inner_join, right_join, full_join as needed)
districts_LBW<- left_join(districts, data, by = "sdist")
merged_data_districts_LBW <- left_join(india_districts, districts_LBW, by = "NAME_2")

# View the merged data
print(merged_data_districts_LBW)
```


```{r}
cleaned_data_merged<- merged_data_districts_LBW %>%filter(!is.na(COLUMN2))

cleaned_data_merged$prevalence_of_SGA[is.na(cleaned_data_merged$COLUMN2)] <-"NA"

# Convert to factor to handle colors in ggplot
cleaned_data_merged$prevalence_of_SGA <- factor(cleaned_data_merged$prevalence_of_SGA)
print(cleaned_data_merged)
```


```{r}
# Clean and prepare the data
cleaned_data_merged <- merged_data_districts_LBW %>%
  mutate(COLUMN2 = as.numeric(as.character(COLUMN2))) %>%
  filter(!is.na(COLUMN2))

# Ensure it's an sf object
cleaned_data_merged <- st_as_sf(cleaned_data_merged)

print(cleaned_data_merged)
```

```{r}
ggplot() +
  geom_sf(data = cleaned_data_merged, aes(fill = COLUMN2), color = NA, size = 0.1) +
  scale_fill_viridis(option = "plasma", direction = -1, name = "LBW Prevalence (%)", 
                     na.value = "grey50",
                     guide = guide_colorbar(barwidth = 15, barheight = 0.5),
                     limits = c(0, 65)) +
  labs(title = "Prevalence of Low Birth Weight (LBW) by District in India") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "bottom",
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )

```


```{r}
# Assuming 95% confidence level, Z-score is 1.96
z_score <- 1.96

# Calculate the confidence intervals
cleaned_data_merged <- cleaned_data_merged %>%
  mutate(
    Lower_CI_LB =  COLUMN2 - z_score * COLUMN4,
    Upper_CI_LB = COLUMN2 + z_score * COLUMN4
  )

# Ensure the CIs are within valid bounds [0, 100]
cleaned_data_merged <- cleaned_data_merged %>%
  mutate(
    Lower_CI_LB = pmax(Lower_CI_LB, 0),
    Upper_CI_LB = pmin(Upper_CI_LB, 100)
  )

```


```{r}
# Calculate CI width
cleaned_data_merged <- cleaned_data_merged %>%
  mutate(CI_width_LB = Upper_CI_LB - Lower_CI_LB)

# Determine limits
max_width_LB <- max(cleaned_data_merged$CI_width_LB)
min_width_LB <- min(cleaned_data_merged$CI_width_LB)
limits_LB <- c(min_width_LB, max_width_LB)
limits_LB
```


```{r}
ggplot() +
  geom_sf(data = cleaned_data_merged, aes(fill = CI_width_LB), color = NA, size = 0.1) +
  scale_fill_viridis(option = "plasma", direction = -1, 
                     name = "CI Width (%)", 
                     na.value = "grey50",
                     guide = guide_colorbar(barwidth = 15, barheight = 0.5),
                     limits = c(0, 35)) +  # Adjusted based on maximum CI_width_LB value
  labs(title = "Width of 95% Confidence Intervals for LBW Prevalence by Districts in India") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "bottom",
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )


```






```{r}
create_interactive_state_map <- function(state_name, cleaned_data_merged) {
  # Filter data for the specific state
  state_data <- cleaned_data_merged %>%
    filter(NAME_1 == state_name)
  
  # Convert to an interactive map
  map <- leaflet(state_data) %>%
    addTiles() %>%
    addPolygons(
      fillColor = ~colorNumeric("plasma", COLUMN2, reverse = TRUE)(COLUMN2),
      color = "white", 
      weight = 1,
      opacity = 1,
      fillOpacity = 0.7,
      popup = ~paste0(
        "District: ", NAME_2, "<br>",
        "LBW Prevalence: ", round(COLUMN2, 2), "%<br>",
        "CI: ", round( Lower_CI_LB, 2), "-", round(Upper_CI_LB, 2), "%"
      )
    ) %>%
    addLegend(
      "bottomright", 
      pal = colorNumeric("plasma", NULL, reverse = TRUE),
      values = ~ COLUMN2,
      title = "LBW Prevalence (%)",
      opacity = 1
    )
  
  # Add title and subtitle using HTML
  title_html <- tags$div(
    tags$h3(paste("Prevalence of Lower Birth Weight (LBW) in", state_name))
  )
  
  map <- map %>%
    addControl(title_html, position = "topright", className = "map-title")
  
  # Custom CSS for the title
  css <- "
    .map-title {
      font-weight: bold;
      text-align: center;
      background: white;
      padding: 5px;
      border-radius: 5px;
      box-shadow: 0px 0px 5px rgba(0,0,0,0.2);
    }
    .leaflet-control {
      background: none;
      border: none;
    }
  "
  
  map <- map %>%
    htmlwidgets::onRender("
      function(el, x) {
        var css = `${css}`;
        var head = document.head || document.getElementsByTagName('head')[0];
        var style = document.createElement('style');
        style.type = 'text/css';
        if (style.styleSheet) {
          style.styleSheet.cssText = css;
        } else {
          style.appendChild(document.createTextNode(css));
        }
        head.appendChild(style);
      }
    ")
  
  map
}

# Get unique state names from the cleaned_data_merged dataset
state_names <- unique(cleaned_data_merged$NAME_1)

# Create interactive maps for all states
for (state in state_names) {
  map <- create_interactive_state_map(state, cleaned_data_merged)
  saveWidget(map, paste0(state, "LBW_SGA_map.html"), selfcontained = TRUE)
}



```










```{r}
# Ensure the CRS is in a format leaflet can use
cleaned_data_merged <- st_transform(cleaned_data_merged, 4326)

# Create a color palette using "inferno"
pal <- colorNumeric(
  palette = "inferno",  # Using inferno palette
  domain = cleaned_data_merged$COLUMN2,
  reverse = TRUE  # Reverse the color scale
)

# Create the formatted labels
cleaned_data_merged$label <- paste0(
  "State: <strong>", cleaned_data_merged$NAME_1, "</strong><br>",
  "District: <strong>", cleaned_data_merged$NAME_2, "</strong><br>",
  "Prevalence: <strong>", round(cleaned_data_merged$COLUMN2, 2), "%</strong><br>",
  "95% CI: <strong>", round(cleaned_data_merged$Lower_CI_LB, 2), "% - ", round(cleaned_data_merged$Upper_CI_LB, 2), "%</strong>"
)

# Create the map
map <- leaflet(cleaned_data_merged) %>%
  addTiles(urlTemplate = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png") %>%  # Replace with a stable tile server URL
  addPolygons(
    fillColor = ~pal(COLUMN2),
    weight = 1,  # Reduced weight for the outlines
    opacity = 1,
    color = "#B0B0B0",  # Light gray color for the outlines
    dashArray = "3",
    fillOpacity = 0.7,
    highlightOptions = highlightOptions(
      weight = 3,  # Highlight weight is also reduced
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = ~lapply(label, htmltools::HTML),  # Use the new formatted labels
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    pal = pal,
    values = ~ COLUMN2,
    opacity = 0.7,
    title = "LBW Prevalence (%)",
    position = "bottomright"
  )

# Save the map to an HTML file
saveWidget(map, file = "LBW_prevalence_map.html")

# Display the map
map

```




```{r}
create_state_map <- function(state_name, cleaned_data_merged) {
  # Filter data for the specific state
  state_data <- cleaned_data_merged %>%
    filter(NAME_1 == state_name)
  
  # Create the map
  ggplot() +
    geom_sf(data = state_data, aes(fill = COLUMN2), color = "white", size = 0.1) +
    scale_fill_viridis(option = "plasma", name = "LBW Prevalence (%)", 
                       na.value = "grey50",
                       guide = guide_colorbar(barwidth = 15, barheight = 0.5)) +
    labs(title = paste("Prevalence of Low Birth Weight (LBW) in", state_name),
         subtitle = "Based on NFHS Data") +
    theme_minimal() +
    theme(
      plot.title = element_text(hjust = 0.5, face = "bold"),
      legend.position = "bottom",
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      panel.grid = element_blank()
    )
}

# First, get unique state names from the cleaned_data_merged dataset
state_names <- unique(cleaned_data_merged$NAME_1)

# Now, create maps for all states
for (state in state_names) {
  map <- create_state_map(state, cleaned_data_merged)
  print(map)
  ggsave(paste0(state, "_SGA_map.png"), map, width = 10, height = 8, dpi = 300)
}

```


## Fay-Herriot model for LBW


```{r}
LBW_data <- cleaned_data_merged %>%
  rename(
    LBW_prevalence = COLUMN2,
    LBW_standarderror = COLUMN4
  )
```



```{r}
# Compute sampling variances from standard errors
LBW_data <- LBW_data  %>%
  mutate(LBW_sampling_variance =  LBW_standarderror^2)

print (LBW_data)
```



```{r}
LBW_data <- as.data.frame(LBW_data)

library(sae)

# Fit the Fay-Herriot model
LBW_fh_model <- try(mseFH(
  formula = LBW_prevalence ~ 1, 
  vardir = LBW_sampling_variance, 
  data = LBW_data
))

LBW_fh_model
```



```{r}
# Extract the results
LBW_data$LBW_FH_estimate <- LBW_fh_model$est$eblup

# Extract MSE values and add them to GROW_data
LBW_data$LBW_MSE <- LBW_fh_model$mse

LBW_data
```




```{r}
library(gridExtra)

# Scatter plot comparing original prevalence with FH estimates
ggplot(LBW_data, aes(x = LBW_prevalence, y = LBW_FH_estimate)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
  labs(x = "Original Prevalence", y = "Fay-Herriot Estimate",
       title = "Comparison of Prevalence of LBW and Fay-Herriot Estimates")

# Histograms
p1 <- ggplot(LBW_data, aes(x = LBW_prevalence)) +
  geom_histogram(bins = 30, fill = "blue", alpha = 0.5) +
  labs(title = "Prevalence of LBW", x= "Prevalence")

p2 <- ggplot(LBW_data, aes(x = LBW_FH_estimate)) +
  geom_histogram(bins = 30, fill = "red", alpha = 0.5) +
  labs(title = "Fay-Herriot Estimates of LBW", x= "FH_estimate")

grid.arrange(p1, p2, ncol = 2)

```
```{r}
# Model Diagnostics

# Calculate residuals
LBW_data$residuals <- LBW_data$LBW_prevalence - LBW_data$LBW_FH_estimate

# Residual plot
ggplot(LBW_data, aes(x = LBW_FH_estimate, y = residuals)) +
  geom_point() +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  labs(x = "Fitted Values", y = "Residuals",
       title = "Residual Plot for Fay-Herriot Model (Low Birth Weight)")


library(qqplotr)

# Creating QQ plot with ggplot2
ggplot(LBW_data, aes(sample = residuals)) +
  stat_qq() +
  stat_qq_line(color = "red") +
  labs(title = "QQ Plot of Residuals (Low Birth Weight)", x = "Theoretical Quantiles", y = "Sample Quantiles" ) +
  theme(plot.title = element_text(size = 14, margin = margin(b = 10)))

```

```{r}
# Calculate 95% CI for FH estimates
LBW_data$LBW_FH_lower_CI <- LBW_data$LBW_FH_estimate - 1.96 * sqrt(LBW_data$LBW_MSE)
LBW_data$LBW_FH_upper_CI <- LBW_data$LBW_FH_estimate + 1.96 * sqrt(LBW_data$LBW_MSE)

LBW_data
```


```{r}
# Comparison Analysis

# Calculate CI width for original and FH estimates
LBW_data$LBW_FH_CI_width <- LBW_data$LBW_FH_upper_CI - LBW_data$LBW_FH_lower_CI

# Calculate mean CI width for comparison
mean_original_CI_width <- mean(LBW_data$CI_width_LB)
mean_fh_CI_width <- mean(LBW_data$LBW_FH_CI_width)

# Print or plot the comparison
cat("Mean width of original CIs:", mean_original_CI_width, "\n")
cat("Mean width of Fay-Herriot CIs:", mean_fh_CI_width, "\n")

```

```{r}
# Determine limits
max_width <- max(LBW_data$LBW_FH_CI_width)
min_width <- min(LBW_data$LBW_FH_CI_width)
limits <- c(min_width, max_width)
limits
```

```{r}
# Compare CI widths
ggplot(LBW_data, aes(x = CI_width_LB, y = LBW_FH_CI_width)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
  labs(x = "Original CI Width", y = "Fay-Herriot CI Width",
       title = "Comparison of 95% CI Widths of LBW and Fay-Herriot Model ")
```


```{r}
# Convert 'prevalence of SGA' to numeric, replacing "NA" strings with actual NA values
LBW_data <- LBW_data %>%
  mutate( LBW_FH_estimate = as.numeric(as.character(LBW_FH_estimate)))

# Remove rows where 'prevalence of SGA' is NA
LBW_data <- LBW_data %>%
  filter(!is.na(LBW_FH_estimate))

# Ensure it's an sf object
LBW_data <- st_as_sf(LBW_data)
```



```{r}
ggplot() +
  geom_sf(data = LBW_data, aes(fill = LBW_FH_estimate), color = NA, size = 0.1) +
  scale_fill_viridis(option = "plasma", direction = -1, name = "LBW Prevalence through smoothing (%)", 
                     na.value = "grey50",
                     guide = guide_colorbar(barwidth = 15, barheight = 0.5),
                     limits = c(0, 65)) +
  labs(title = "Prevalence of Low Birth Weight by Districts in India",
       subtitle = "After Fay-Herriot model") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "bottom",
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )


```


```{r}
ggplot() +
  geom_sf(data = LBW_data, aes(fill = LBW_FH_CI_width), color = NA, size = 0.1) +
  scale_fill_viridis(option = "plasma", direction = -1, 
                     name = "CI Width (%)", 
                     na.value = "grey50",
                     guide = guide_colorbar(barwidth = 15, barheight = 0.5),
                     limits = c(0, 35)) +  # Adjusted based on maximum CI_width value
  labs(title = "Width of 95% Confidence Intervals for LBW Prevalence by Districts in India",
       subtitle = "After Fay-Herriot model") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "bottom",
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )


```
